### ISSUE TITLE
feat: add Write Buffer, replication and subscriptions

### ISSUE THREAD

**Issue by pauldix** [influxdata/influxdb_iox#1073]
An IOx server can act as a buffer for incoming writes and deletes. A buffer server can replicate writes synchronously as they arrive to other buffer servers for fault tolerance. The buffer serves as a way to send the raw stream of writes and deletes to object storage for later use or for downstream subscribers to either pull or get pushed these writes asynchronously outside of the client's request/response lifecycle. Subscribers can get the entire stream of writes or filter by table name and/or a predicate.

[This document](https://docs.google.com/document/d/1wVGOCMjLlDM0QvKotbqmGGwe0V_4yaJurPXM7c4-Tw8/edit?usp=sharing) describes how we'll be using the write buffer functionality to provide replication and fault tolerance.

This issue will serve as the tracker for the overall feature delivery. To get this done as a user facing feature, we'll need to deliver many of the following issues. However, some of them may be sequenced for later work as not all of this will be required for the MVP.

* [x] #1086 - Create flatbuffer schema for Write Buffer
* [x] #1087 - Write line protocol to sharded entries converter
* [x] #1158 - Refactor MB to receive SequencedEntry writes
* [ ] #1157 - Implement Logical Clock and refactor WAL Buffer -> Write Buffer
* [x] #1088 - Router to Write Buffer API
* [ ] (issue) - Write Buffer replication API (with logical clocks)
* [ ] (issue) - Add schema validation to Write Buffer layer
* [ ] (issue) - Subscriptions CRUD API
* [ ] (issue) - Write Buffer to downstream subscriber push API
* [ ] (issue) - Write Buffer pull API
* [ ] (issue) - Write Buffer consistency checks API
* [ ] (issue) - Refactor Write Buffer segment persistence to object store (done already, but needs updating based on this)
* [ ] (issue) - Recover segments from object store
* [ ] (issue) - Ensure MB reorders writes received out of order on query
* [ ] (issue) - Ensure MB -> RB or reorders writes received out of order
* [ ] (issue) - Partial segment persistence on local storage (WAL of  sorts)
* [ ] (issue) - Local storage segment to object storage
* [ ] (issue) - Retrieve segments from object storage when subscriber pull request goes farther back than buffer
