### ISSUE TITLE
Expose Prometheus IOx metrics

### ISSUE THREAD

**Issue by e-dard** [influxdata/influxdb_iox#1370]
IOx needs to expose key metrics via a metrics endpoint using the prometheus exposition format. This allows IOx to be monitored when deployed.

This PR covers all the various work that we might want to do to make that happen:

- [x] Add our own metrics abstraction to make it easier to consistently instrument the IOx application: #1276.
- [x] Expose counters  #1276;
- [x] Expose historgrams #1345;
- [x] Expose gauges. #1390  #1392
- [x] Instrument the write path (requests, points ingested, errors, size ingested etc)
- [x] Instrument the HTTP API (requests, errors, duration) #1276
- [x] Instrument the gRPC API (requests, errors, duration on all operations, e.g., read_filter, meta queries #1371
- [x] Instrument chunk movement rates through system: #1287
- [x] Instrument chunk sizes, rows, column composition etc
- [x] Instrument time-range of data in system.
