### ISSUE TITLE
Avoid serializing parquet writing

### ISSUE THREAD

**Issue by crepererum** [influxdata/influxdb_iox#1821]
Currently we take a database-wide transaction lock while writing payload data to parquet files (not just while adding the resulting files to the catalog). This could be avoided.

# Plan
- [x] Make `rebuild` not rely on transaction information stored in parquet files (#1823)
- [x] Make `cleanup` not use the transaction lock (#1824)
- [ ] Remove transaction information from parquet file (but keep a timestamp or something similar for data lineage) (#1836)
- [ ] Move parquet writing out of the transaction scope (but remember to keep it inside the cleanup lock, see step 2) (#1836)
