### ISSUE TITLE
Chunk time_of_last_write and time_of_first_write should not be options

### ISSUE THREAD

**Issue by pauldix** [influxdata/influxdb_iox#1927]
A chunk cannot exist without data written into it, thus the `time_of_last_write` and `time_of_first_write` should not be options. `CatalogChunk` is what currently has this as options and it may be doing this because of how those chunks are created. However, if the source is the MUB, RUB, or a Parquet file, there should always be a time for the first write and time for the last.

Updating this is likely a change across a number of different areas.

* [x] #2086 Chunks from object store will need to be updated to persist this information somewhere in their metadata. [See initialization here](https://github.com/influxdata/influxdb_iox/blob/main/server/src/db/catalog/chunk.rs#L310-L338)
* [x] #1940 MUB chunks should keep track of their first/last write times
* [x] MUB chunks when converted to CatalogChunk should use the actual information from the MUB, not the current time [here](https://github.com/influxdata/influxdb_iox/blob/main/server/src/db/catalog/chunk.rs#L242-L266) 
  * Done in https://github.com/influxdata/influxdb_iox/pull/1997
* [x] RUB chunks converted to CatalogChunk will need it [here](https://github.com/influxdata/influxdb_iox/blob/main/server/src/db/catalog/chunk.rs#L271-L307)
* ~~Add first/last write times to `TableSummary`~~ Partially done, partially decided to go in a different direction
* [x] #2122 Actually make first/last write times on CatalogChunk required
* [ ] Refactor to try to make first/last write times on CatalogChunk the only source of this information

To me this is all pointing to something missing in `TableSummary` which is this write information. So adding it to that and updating these spots might be the best way to go?

This is part of making the lifecycle easier to understand and work with in the code (see #1914).

**Comment by tustvold** [comment]
So currently these timestamps are the timestamps of writes to that particular chunk, not the timestamps of the data itself. This dates from a time when the lifecycle needed this information, it now doesn't, and so I was just planning to remove it as extraneous cruft...

If we do decided to keep it, when compacting chunks I guess you take the min and max of the inputs?

**Comment by alamb** [comment]
See also #1846  and #1954
