### ISSUE TITLE
Support Soft Delete

### ISSUE THREAD

**Issue by NGA-TRAN** [influxdata/influxdb_iox#2396]
# Rationale
This is a part of https://github.com/influxdata/influxdb_iox/issues/2395. Refer to [this delete design document ](https://docs.google.com/document/d/1AKJYEvarjRxpnRx4q5XwcrhVpQtlVcLO0ltPjg_5aoU/edit#) for use cases, design ,  and related features.

# Implementation  Check List 
There are three main actions for soft delete, each has its own checklist

1. Issue delete

- [x]  Implement gRPC management API: `delete(db_name, table_name, predicate)` to issue the delete
- [x] #2463, #2667 and  #2567 
- [x] Parse specific range of timestamps
- [x] #2478
- [x] Add `delete_predicates` field into chunk catalog. Open MUB chunks must be closed/frozen with this event.
- [x] #2493
- [x] #2518 
- [x]  #2550
- [x] #2703 
- [x] Current we delete [start, stop). Need to make stop inclusive [start, stop] 
- [x] @e-dard will make [delete time range](https://github.com/influxdata/influxdb_iox/blob/d50f41c4271127606202fe5d495c7294b02bf206/predicate/src/predicate.rs#L176) and [query time range](https://github.com/influxdata/influxdb_iox/blob/c77f1ef4e290da66ab63396254ccb84db4bdf4cf/data_types/src/timestamp.rs#L1-L11) consistent #2734 
- [x] #2627 -> @crepererum 

2. Query none-deleted-data
- [x] Push delete predicates down to RUB and OS to pruning data as early as possible. Note that MUB has not yet supported predicate pushdown/pruning. OS only supports pruning. RUB  supports delete predicates push down.  This will be done at [`read_filter`](https://github.com/influxdata/influxdb_iox/blob/f7792aafe68edcb3bce01778bcf5f85bc844e64d/server/src/db.rs#L2504). Add  the following signature to be able to apply `select_predicate` and `delete_predicates` separately if needed.

```
pub fn read_filter(
   &self,
   select_predicate: Predicate,
   select_columns: Selection<'_>,
   delete_predicate: Predicate, 
)
```
- [x] At scan step, apply delete predicates on appropriate chunks
- [x] Optimize scan for chunks with no delete predicates #2603
- [x] Add delete_predicates as a parameter to influxrpc's operators #2751 &br #2548. -> @NGA-TRAN
- [x] Not throw error when all of rows of a OS chunk are soft deleted #2546 

3. Using statistics to read data
-  [x] With soft delete, the chunk's min, max, count are no longer accurate and should not be used to answer queries.
 Recently, statistics (count, min and max) is implemented in [DataFusion (for SQL queries) ](https://github.com/apache/arrow-datafusion/pull/719). The rewrite is enabled if the table provides says that it returns exact  statistics, which IOx always reports [here](https://github.com/influxdata/influxdb_iox/blob/81ef17b02ed50f1eee438076c4d1164afd9dbfc1/query/src/provider.rs#L287-L291). If deletes are present we can either not report statistics at all or say they are not exact
#2744 --> @NGA-TRAN 

4. Stay compatible with Cloud 2? 
- [x] Do we want to stay compatible with Influx Cloud 2 by allowing the column data type to change if all of its data is deleted?  -> @NGA-TRAN   
   - @e-dard has played with Cloud 2 
      - if you write `temp` as a float:  `disk,server=a temp=22.3343`
      -  then delete it:  `influx delete --bucket edd --predicate "_field=temp" --start 2020-08-24T00:00:00Z --stop 2021-08-31T23:00:00Z`
      - then you are able to insert into `temp` integer data: `disk,server=a temp=100i`
   - We need to think through before having a design for this because we still store soft deleted data which prevents us from changing the column data type.
        -> This will be done in different tickets (will link when we finalize the plan). See [on-going discussion](https://influxdata.slack.com/archives/CRK9M8L5Q/p1633443950393100) and [Thoughts around TSM to IOx feature misalignment](https://docs.google.com/document/d/1JSK9Otl33GGKkiHjMYTDJfCakZjL6WF2OStsv9k8RVQ/edit#heading=h.43nnj5776x81)

We have decided to mix DML with DDL so mark this task is doe without doing anything

**Comment by NGA-TRAN** [comment]
Have moved  #2629 and  #2731 out of this ticket as they are tracked separately
