### ISSUE TITLE
Meta-issue: Floating Databases

### ISSUE THREAD

**Issue by carols10cents** [influxdata/influxdb_iox#2672]
This is an implementation plan for the floating database design that will enable moving ownership of a particular database to a particular IOx server node, without needing to copy files in object storage.

## Assumptions

This proposal is written with the following in mind:

- It's ok to break backwards compatibility of object storage for now; wiping the catalog on deploy is still acceptable
- Intermediate states should still be functional so that PRs can be merged, deployed, and used along the way
  
## Plan

- [x] https://github.com/influxdata/influxdb_iox/issues/2675
- [x] https://github.com/influxdata/influxdb_iox/issues/2762
- [x] https://github.com/influxdata/influxdb_iox/issues/2975
- [x] https://github.com/influxdata/influxdb_iox/issues/2676
- [x] https://github.com/influxdata/influxdb_iox/issues/2677
- [x] https://github.com/influxdata/influxdb_iox/issues/2678
- [x] https://github.com/influxdata/influxdb_iox/issues/2679
- [x] https://github.com/influxdata/influxdb_iox/issues/3110
- [x] https://github.com/influxdata/influxdb_iox/issues/2680  
- [x] https://github.com/influxdata/influxdb_iox/issues/3037

## Deliberately not included in this meta-issue

- A "Garbage Collect" operation, that shouldn't be IOx's responsibility
- A "Rename database" operation, it should be trivial to do after this is done but isn't really part of this
- A "List all owned and unowned databases" command; this might not be IOx's responsibility
- Providing and storing context on the ownership transaction records was deferred: https://github.com/influxdata/influxdb_iox/issues/3095

**Comment by alamb** [comment]
> QUESTION: If we've added active database a to the database list, then we find another active database with a different UUID but also with the name a in its rules.pb, what should happen

I suggest "Put both a databases in an error state" as it needs operator intervention to sort out which one is the real "a"

Other suggestions: use a name like `server.pb` or `owner.pb` for the "who do I belong to"  file for a database. `floating.pb` I feel is less precise and would be confusing to newcomers. 

> QUESTION: database name or database UUID?

since most other APIs are in terms of database name, that is probably the most consistent and easiest for humans to use. 
If there is some usecase for dealing with the UUID directly, perhaps we can have the API support either UUID or name

> QUESTION: Should the server first check and make absolutely sure it is the current owner of this database by verifying the database's floating.pb backlink points to the current server's ID?

I vote yes -- the rationale is to try and verify the state prior to updating those files to catch concurrent modifications or other shenanigans (even though we will never catch all possible concurrent modifications.



Another comment: using `OwnershipTransaction` etc to update `floating.pb` seems overly complicated to me (than just writing the new values), but I realize that was in the original design document and @mkmik  and @crepererum  may have other thoughts. 

> QUESTION: Remove the Delete/Restore Database CLI and gRPC API commands, or make them aliases for the disown/adopt database command/API?

I personally suggest removing the Delete/Restore database to avoid confusion, but I think @pauldix  should weigh in on the UX here

**Comment by mkmik** [comment]
> Another comment: using OwnershipTransaction etc to update floating.pb seems overly complicated to me (than just writing the new values), but I realize that was in the original design document and @mkmik and @crepererum may have other thoughts.

The rationale for this additional complication is that without it, it would be very hard to recover the orchestrator state in case the orchestrator state gets lost. For example consider this sequence: a) rebalance automation (or human) causes a move of database "foo" from one server to another b) conductor initiates a disown operation c) current db owner updates floating.pb conf d) conductor state gets destroyed (e.g. somebody wipes out the database and restores an old backup) e) we now have a "dangling database" foo which is hard to recover because all the information about this held in the orchestrator. The transaction log in the floating.pb allows operators to recover that state (if you squint, it's a kind of orchestrator state backup)

**Comment by mkmik** [comment]
> QUESTION: Remove the Delete/Restore Database CLI and gRPC API commands, or make them aliases for the disown/adopt database command/API?

I think a "delete" operation meant for end users who directly operate the IOx database makes sense. The Floating Databases design document even suggests that we could keep the DeleteDatabase API and implement it in terms of `DisownDatabase` internally and pass a `DatabaseTombstone` context to be stored in the ownership transaction log.

```
// This message is added to the floating database transaction context when a disown
// operation is the result of a user performing a DeleteDatabase operation (which is
// otherwise implemented in terms of the DisownDatabase operation).
message DatabaseTombstone {
}
```

**Comment by carols10cents** [comment]
> The Floating Databases design document even suggests that we could keep the DeleteDatabase API and implement it in terms of `DisownDatabase` internally and pass a `DatabaseTombstone` context to be stored in the ownership transaction log.

Wait, so when the Disown API is used (instead of Delete), there *isn't* a `DatabaseTombstone` context written?

**Comment by mkmik** [comment]
> QUESTION: If we've added active database a to the database list, then we find another active database with a different UUID but also with the name a in its rules.pb, what should happen?

@carols10cents 

I vote for "Put both a databases in an error state"

**Comment by mkmik** [comment]
> > The Floating Databases design document even suggests that we could keep the DeleteDatabase API and implement it in terms of `DisownDatabase` internally and pass a `DatabaseTombstone` context to be stored in the ownership transaction log.
> 
> Wait, so when the Disown API is used (instead of Delete), there _isn't_ a `DatabaseTombstone` context written?

When the Disown API is used, then the caller chooses what to put in the context. Usually the orchestrator tool (e.g. conductor) will have their own proto message that marks the operation as being done by conductor and gives some context (e.g. disowned as part of the migration from server 1 to server 2)

**Comment by mkmik** [comment]
> QUESTION: database name or database UUID?

( @carols10cents )

IIUC @pauldix set a strong requirement: the database name *is* the ID of a database, as far as an individual IOx instance is concerned. The UUID should be used to distinguish other instances of that same "database" (e.g. other shards/replicas/versions of the same db)

The disown API asks an existing database to relinquish a database it owns and operates, and which can thus be uniquely
identified by name.

The adopt API however needs to operate either on full objectstore paths or by some part thereof. We choose to use the uuid part instead of opening up (yet) the possibility of adopting databases from arbitrary locations (which may be a useful feature but now adds unnecessary complications to the story).

This desired API is correctly captured in the design document:

```
// Disown the databases matching the db_name id.
message DisownDatabaseRequest {
  // the name of the database
  string db_name = 1;

...

message DisownDatabaseResponse {
  // the uuid of the disowned database
  string uuid = 1;
}
```

The reply contains the uuid as a convenience: it allows a caller to disown the database and adopt it somewhere else without having to remember to first get the database in order to read the uuid from it.

**Comment by alamb** [comment]
> The transaction log in the floating.pb allows operators to recover that state (if you squint, it's a kind of orchestrator state backup)

I defer to you here. I don't fully understand the usecase (aka what state the orchestrator would need to recover when humans are messing around with db assignment) but I don't think it is critical at the moment for me to do so

**Comment by mkmik** [comment]
> > The transaction log in the floating.pb allows operators to recover that state (if you squint, it's a kind of orchestrator state backup)
> 
> I defer to you here. I don't fully understand the usecase (aka what state the orchestrator would need to recover when humans are messing around with db assignment) but I don't think it is critical at the moment for me to do so

I do agree it's not strictly necessary to implement this in the first phase. It was a response to a legitimate worry that mixing up all the databases from various owners into the same pool (the same objectstore directory, with each db into a dir with uuid) will make it hard to figure out which database is which, in the event that we lose track of owners. I personally think the additional complexity is relatively low and it may be worth doing it right now, but I defer to whoever ends up implementing this to choose when to do it.

**Comment by NGA-TRAN** [comment]
>> QUESTION: If we've added active database a to the database list, then we find another active database with a different UUID but also with the name a in its rules.pb, what should happen

> @alamb's answer: I suggest "Put both a databases in an error state" as it needs operator intervention to sort out which one is the real "a"

I think UUID is  for us to manage the DBs. User only needs to know DB name. Hence, I think we need to check DB name and throw error if already exists. If 2 DBs with the same name are created at exactly the same time, by using transaction, we will only allow one created successfully, the other will get error.

**Comment by mkmik** [comment]
> > > QUESTION: If we've added active database a to the database list, then we find another active database with a different UUID but also with the name a in its rules.pb, what should happen
> 
> > @alamb's answer: I suggest "Put both a databases in an error state" as it needs operator intervention to sort out which one is the real "a"
> 
> I think UUID is for us to manage the DBs. User only needs to know DB name. Hence, I think we need to check DB name and throw error if already exists. If 2 DBs with the same name are created at exactly the same time, by using transaction, we will only allow one created successfully, the other will get error.

We could try to resolve the conflict automatically, but I think it may premature to think about it now.

**Comment by carols10cents** [comment]
I was about to write up some details on the difference between delete/disown, but I think I'm getting a bit too in the weeds.

Does the overall plan look good, that is, should I create separate issues for the 7 top-level bullet points where we can get into details? Am I missing any big pieces? Are they broken down in a reasonable way?

**Comment by mkmik** [comment]
The overall plan looks good!

One thought though:

> Add a "List all databases and their owners" gRPC and CLI API

Not sure if this should live in IOx. Eventually we may want to implement a "multi-bucket" adoption mechanism that allows servers to adopt objects from another s3 bucket (provided we also ensure it has the access rights somehow); when we do that, it's not longer necessarily true that each iox node can "see everything" and having such an API may become confusing.

Perhaps we could implement this functionality as a library function we can call from conductor?

**Comment by carols10cents** [comment]
This can be closed now as this project was finished.
