### ISSUE TITLE
Persist a `PersistingBatch` to a ParquetFile

### ISSUE THREAD

**Issue by NGA-TRAN** [influxdata/influxdb_iox#3491]
# Rationale
Now we have well defined data structures and processes for [Ingester](https://github.com/influxdata/influxdb_iox/tree/main/ingester/src), this ticket is to persist a [PerstingBatch](https://github.com/influxdata/influxdb_iox/blob/4728d9e7623f964bb197eb01b735d69f64612f71/ingester/src/data.rs#L128) to a  parquet file in the Object Store.

## Steps: 
- [x] Compaction : done in PRs: #3514, #3519 , #3535 , #3542 
- [x] Persistence: defined in #3513 , #3514 
- [x] Update Catalog & remove in-memory data #3564
