### ISSUE TITLE
Implementation checklist when the Ingester gets a request from a Querier

### ISSUE THREAD

**Issue by NGA-TRAN** [influxdata/influxdb_iox#3637]
__Use case:__

When an Ingester gets this request from a Querier 

```rust
struct IngesterQueryRequest {
  // we can lookup in memory by the table
  table: String,
  // only select the columns we care about
  columns: Vec<String>,
  // start time of the query
  min_time: i64,
  // end time of the query
  max_time: i64,
  // predicate for filtering
  predicate: Option<Predicate>,
  // optional to only return rows with 
  // a sequence number > than this
  greater_than_sequence_number: Option<u64>
}
```

It will send appropriate in-memory data of that table back.  Here is a list of tasks to make it happen:

- [x] gRPC to get request and send data #3616 
- [x] Prepare data to send  #3640
- [x] Projection pushdown: to filter data from Ingester before sending to Querier: make QueryableBatch's [read_filter](https://github.com/influxdata/influxdb_iox/blob/d2ccf23263c775db7388c526681f9af9a88ca440/ingester/src/query.rs#L191) only reads given column  specified in `selection`.#3693
- [x] Predicate pushdown:  to filter data from Ingester before sending to Querier: make QueryableBatch's [read_filter](https://github.com/influxdata/influxdb_iox/blob/d2ccf23263c775db7388c526681f9af9a88ca440/ingester/src/query.rs#L191) to apply `predicate` on needed columns to reduce data. #3719 
- [x] Build a query plan to apply the projection & predicate pushdowns #3729

**Comment by NGA-TRAN** [comment]
Close this since all of its tasks are available
