### ISSUE TITLE
Implement NG Compactor

### ISSUE THREAD

**Issue by NGA-TRAN** [influxdata/influxdb_iox#3904]
# Rationale 
The is an epic for building [NG Compactor](https://docs.google.com/document/d/1lfILhw5ckzTlXFOk7VXKQOiz3TvDDlx-tdCgQ0YiG8E/edit).

### Prerequisites
- [x] #3945 

### Must-Haves Before Deployment
- [x] #3947
- [x] #3946
- [x] #3949
- [x] #3948
- [x] #3907 
- [x] #3999 
- [x] #3950
- [x] #3951
- [x] #3952
- [x] #3953
- [x] #3954
- [x] #4059
- [x] #4093
- [x] Scheduler & Related Deployment
    - [x] https://github.com/influxdata/influxdb_iox/pull/4107
    - [x] Make a config parameter to replace LEVEL_UPGRADE_THRESHOLD_NANO & SPLIT_PERCENTAGE. Done in #4139 
    - [x] https://github.com/influxdata/influxdb_iox/issues/4120
    - [x] Make compact run multithreaded when possible. Done in #4139 
- [x] Compactor Metrics. Done in #4139 
       
### Needed Optimizations
- [x] #3968
- [x] When #3968 available, use available sort keys of the parquet files during compaction and keep the new files's sort keys consistent with the old one, too https://github.com/influxdata/influxdb_iox/issues/4249
- [ ] #4205 
- [ ] Schedule to apply tombstones to cold partitions after #4205 available
- [x] #4101
- [x] #4324 
- [x] #4192
- [ ] Schedule to invoke hard delete when #3964 is implemented. Extra note: from [migration doc](https://docs.google.com/document/d/1VXibXMJyGhs7Cqbf_TVSEIr7uVuSjCc-zlvam-HEyR0/edit#), the head delete must happen before a [cap config setup
](https://github.com/influxdata/idpe/issues/12309)

### Issues In Production Mirror Testing
- [x] #4585 
- [x] #4838 

### Needed optimization for Ingester, Compactor & Querier
- [x] Many features/tasks: https://github.com/influxdata/influxdb_iox/issues/4283
- [x] Remove parquet Metadata 
     - [x] #4262
     - [x] #4285 
- [x] #4790. This depends on #4915
- [x] #4915
- [x] #4940 
- [ ] Compactor does more so Ingster can do less: refer to this [Ingester 970 issue](https://github.com/influxdata/conductor/issues/970#issuecomment-1156829377). Probably to choose which partition to compact first and how to not starving compacting other partitions
- [ ] Reduce calling SQL query that selects Compactor candidates. Seems like the issue in #4913. Preliminary investigation, these are 2 queries that I suspect the Compactor calls the most (which seem not the top queries listed in 4913):
[list_by_partition_not_to_delete_with_metadata](https://github.com/influxdata/influxdb_iox/blob/70337087a83827959a88668d2e51fe225833b246/iox_catalog/src/postgres.rs#L1706)
[level_0](https://github.com/influxdata/influxdb_iox/blob/70337087a83827959a88668d2e51fe225833b246/iox_catalog/src/postgres.rs#L1627)

### Future Improvements
- [ ] Hierarchical partition to further collapse cold partitions. For example, data of latest week is partitioned by day. Data of latest month but not in latest week is partitioned  day by week. Data of latest year but not in latest month is partitioned by month. Data of other years is partitioned by year.

**Comment by alamb** [comment]
I think this ticket is likely "done enough" and recommend we close it
