### ISSUE TITLE
NG Querier: Epic for Run query_tests against querier

### ISSUE THREAD

**Issue by alamb** [influxdata/influxdb_iox#3934]
The idea here is to update the `query_test` crate to add coverage of the new querier component 

the definition of done is that some (exact subset tbd) of the query tests will also load data via the new ng flow (aka parquet files in the new Catalog, perhaps via the ingester), run queries against it, and validate that the answers are correct

Some possible steps:
- [x] Decouple `query_test` from using `Db` directly (either use a trait or an Enum) to prepare to use new Querier
- [x] For each existing scenario, put the data into a parquet file, create the appropriate entry in the data in the `iox_catalog` and instantiate a querier, and then runs the query tests against it
- [x] Add additional data setup to query_tests: Data in Multiple Parquet Files
- [ ] #4296
- [ ] Add additional data setup to query_tests: Data in Ingester structures + Parquet
- [ ] Add additional data setup to query_tests: different cache contents, etc
- [ ] #4459

**Comment by alamb** [comment]
cc @tustvold  and @crepererum  -- hopefully this captures what we discussed face to face

**Comment by alamb** [comment]
Assigning to @crepererum  as he is cranking along on this

**Comment by crepererum** [comment]
I pause that for now, because I think it would be helpful to have a least a 2nd chunk stage (= ingester) before fully polishing the test framework.

**Comment by alamb** [comment]
I think this is basically not tracking any planned work any more and the querier runs query_tests,  so closing
