### ISSUE TITLE
NG Querier: Proper Cache Layer

### ISSUE THREAD

**Issue by crepererum** [influxdata/influxdb_iox#3985]
Add a proper cache layer that shields the postgres catalog from "each flight/InfluxRPC query results in multiple Postgres queries". Requirements are:

- [x] only cache data that is needed
- [x] work w/ async codebase #3991
- [ ] #4616
- [x] be generic (mostly just take a function that is executed on cache misses) #3991
- [x] TTL #4027
- [ ] #4618
- [ ] #4617
- [x] one cache per topic/object type (no giant cache data structure) #3991
- [x] one cached object may answer multiple requests (e.g. a cached table can answer both ID->name as well as name->ID mappings) #3991
- [x] replaces the current `querier::cache` #3991

~Might use the `cache_loader_async` crate (or not if it doesn't fit).~ Didn't fit, because:

- tests esp. regarding cancellation and panics were basically missing
- complex interface
- we would need to replace/wrap many features (e.g. for metrics, integration with `TimeProvider`, size-based LRU) so there wasn't much left (the semi-tested core logic at most)

**Comment by alamb** [comment]
I am not sure being generic is a requirement for what is worth

Also it is worth thinking about:
1. How will locally caching data in ReadBuffer and Parquet be connected to this system

**Comment by crepererum** [comment]
> I am not sure being generic is a requirement for what is worth

I just don't wanna write the infrastructure stuff (metrics, management controls, LRU/TTL handling) multiple times. I just want something that is consistent and well tested, so I don't need to bother with it all too much when reasoning about the querier.

> How will locally caching data in ReadBuffer and Parquet be connected to this system

IMHO that's just another KV cache. "Cache" per se doesn't have to be "cached in RAM", it can also mean "this is a cached parquet file on disk" (I don't wanna write a caching framework that deals with storage backends or serialization though).

**Comment by crepererum** [comment]
Closing this since the basic work is done and we can use the open tickets to track the concrete open items.
