### ISSUE TITLE
NG Querier: Epic to combine input from catalog and ingester

### ISSUE THREAD

**Issue by alamb** [influxdata/influxdb_iox#3988]
This ticket tracks the overall work to design and connect the querier to the ingester so that not-yet-persisted-data will be visible to queries.

Major items would be:
- [ ]  "service discovery" (aka how will the querier know how to find and talk with the ingester that has data for it): https://github.com/influxdata/influxdb_iox/issues/4144
- [x] At query time, making the call to the ingester, getting the data back, and then connecting to the querier: https://github.com/influxdata/influxdb_iox/issues/3996
- [x] Expose some way to make data readable: https://github.com/influxdata/influxdb_iox/issues/4145

**Comment by alamb** [comment]
Another idea that I think I heard @tustvold  say was to supply the querier with a list of ingesters, and then have the querier as the ingesters which one knows about the namespace it is interested in.

**Comment by NGA-TRAN** [comment]
> Another idea that I think I heard @tustvold say was to supply the querier with a list of ingesters, and then have the querier as the ingesters which one knows about the namespace it is interested in.

Yes, this is an option.

Another very naive option is to just send request to all Ingester and ignore TableNotFound returns

**Comment by mkmik** [comment]
broadcasting (sending to all ingesters) is also a very simple way to handle when we change the number of ingesters.
We could cache the last known mapping of sequencerid to ingestor url and broadcast when that cache entry gets invalidated

**Comment by mkmik** [comment]
however, instead of basing this on errors, the querier could explicitly pass the intended sequence id in the request and the ingester will respond with a structured error code that says "I'm not responsible for this sequencer id" (possibly in the future also including the url of the ingester that is responsible for it)

**Comment by NGA-TRAN** [comment]
@alamb and @tustvold : FYI for you to design this. The Ingester is designed to not necessary know all the Tables it is responsible for. It only knows the tables with data in it in-memory at that moment. Hence if you ask Ingester if it has data for that table, it may say yes or no depening on when you ask

**Comment by mkmik** [comment]
The ingester knows what sequencerIDs it's responsible for; perhaps that's the thing the request is to be predicated on.

**Comment by alamb** [comment]
@crepererum  I believe plans to take a shot at writing this up

**Comment by crepererum** [comment]
Is this done?

**Comment by alamb** [comment]
I think so -- we can track https://github.com/influxdata/influxdb_iox/issues/4144 as a follow on project
