### ISSUE TITLE
NG Querier: End to End testing

### ISSUE THREAD

**Issue by alamb** [influxdata/influxdb_iox#4102]
This is a tracking ticket to get basic end to end tests setup for NG

# Purpose 
The purpose of the end to end tests is to be the highest level "integration" test that can run just within the influxdb_iox repository and makes sure all the various plumbing is connected correctly. It is NOT meant to cover corner cases in implementation, which are better tested in the tests of the various modules

# Structure
Each of these tests starts up IOx as a sub process (aka runs the `influxdb_iox` binary) and manipulates it either via client or APIs. These tests should not manipulate or use contents of any influxdb_iox crates. 

# Current state of affairs:
* `end_to_end`: https://github.com/influxdata/influxdb_iox/blob/alamb%2Ffix_return/influxdb_iox/tests/end_to_end.rs#L1
* `end_to_end_ng`: https://github.com/influxdata/influxdb_iox/blob/alamb%2Ffix_return/influxdb_iox/tests/end_to_end_ng.rs#L1

The [current end to end NG](https://github.com/influxdata/influxdb_iox/blob/alamb%2Ffix_return/influxdb_iox/tests/end_to_end_ng_cases/ng.rs#L15) test verifies that the ingester can return data written by the router. Kudos to @carols10cents  for getting the foundation setup.

# High level plan
I reviewed the scenarios in end_to_end that we need to port, and here is the initial list I came up with

### Basic plumbing tests
- [ ] End to end smoke  test for all-in-one mode (write data, query it back), with CLI and client
- [ ] End to end smoke test for querier: write data to a router, ensure the data gets to parquet, read it back from the querier
- [ ] End to end coverage for grpc write endpoint: https://github.com/influxdata/influxdb_iox/issues/3941
- [ ] End to end  gRPC coverage (https://github.com/influxdata/influxdb_iox/issues/3958) -- port the existing OG tests https://github.com/influxdata/influxdb_iox/blob/main/influxdb_iox/tests/end_to_end_cases/influxrpc.rs#L1
- [ ] End to end flight API (https://github.com/influxdata/influxdb_iox/issues/3958) -- port the existing OG tests https://github.com/influxdata/influxdb_iox/blob/main/influxdb_iox/tests/end_to_end_cases/flight_api.rs#L1
- [ ] TBD: Data life cycle (e.g that data gets into parquet files eventually): https://github.com/influxdata/influxdb_iox/blob/main/influxdb_iox/tests/end_to_end_cases/persistence.rs#L4 - blocked on other stuff probably

### Infrastructure plumbing tests
- [ ] End to end test for logging (port https://github.com/influxdata/influxdb_iox/blob/main/influxdb_iox/tests/end_to_end_cases/influxdb_ioxd.rs#L1)
- [ ] End to end test for metrics: https://github.com/influxdata/influxdb_iox/blob/main/influxdb_iox/tests/end_to_end_cases/metrics.rs#L1
- [ ] End to end test for tracing: https://github.com/influxdata/influxdb_iox/blob/main/influxdb_iox/tests/end_to_end_cases/tracing.rs#L1
- [ ] End to end test for operations API? https://github.com/influxdata/influxdb_iox/blob/main/influxdb_iox/tests/end_to_end_cases/operations_api.rs#L1

# Open questions:
How will the 4+ services that make up NG be controlled in the end to end tests? I'll probably want to create a harness that starts them up and configures them correctly.  We already have the `TestConfig` to configure various individual services but I expect that the common case of starting at least 3 services (router, ingester, and querier) will be needed quite frequently.

**Comment by carols10cents** [comment]
Regarding: 

> - End to end test for operations API? [main/influxdb_iox/tests/end_to_end_cases/operations_api.rs#L1](https://github.com/influxdata/influxdb_iox/blob/main/influxdb_iox/tests/end_to_end_cases/operations_api.rs#L1)

I've investigated, and found the operations_api test is verifying the ability to create, list, and cancel jobs in the job registry through API requests. The only JobRegistry-like structure I see in NG is [in ingester](https://github.com/influxdata/influxdb_iox/blob/14cb2f56741efee171f41ce8ad822bbaf2c4303b/ingester/src/job.rs#L37) - which implements its own JobRegistry rather than using [the job_registry crate](https://github.com/influxdata/influxdb_iox/tree/main/job_registry). The ingester's JobRegistry doesn't appear to yet have methods like `tracked`, which is [what the operations API uses](https://github.com/influxdata/influxdb_iox/blob/14cb2f56741efee171f41ce8ad822bbaf2c4303b/ioxd_database/src/rpc/operations.rs#L131). Therefore, I don't think this needs to be ported right now as the functionality doesn't exist in NG, and I've crossed this item off the list.
