### ISSUE TITLE
Investigation: Compactor cannot catch up with Ingester

### ISSUE THREAD

**Issue by NGA-TRAN** [influxdata/influxdb_iox#4585]
# Summary of issues:
1. Compact a partition of large files is so slow
2. Compactor buffers data of parquet files instead of streaming which lead to huge memory needed 
4. The current setup makes the concurrency level  is very low 1

# TODOs

- [x] #4883
- [x] #4869 
- [x] influxdata/conductor#969 
- [x] influxdata/influxdb_iox#4761 
- [x] influxdata/influxdb_iox#4762
- [x] influxdata/influxdb_iox#4695
- [x] influxdata/influxdb_iox#4696 
- [x] influxdata/influxdb_iox#4671 
- [x] influxdata/influxdb_iox#4596 - @NGA-TRAN 
- [x] influxdata/influxdb_iox#4324  - @domodwyer 
- [x] influxdata/influxdb_iox#4594 - @mkmik , @NGA-TRAN , @domodwyer 

# Observation
[Full Dashboard](https://grafana.prod01-eu-central-1.aws.influxdata.io/d/z7-FhLsnk/compactor?orgId=1)

Our current tests on one Compactor that compacts all files of 100 sequencers ingested by 4 Ingesters shows that the Compactor cannot catch up with the Ingester and, every compact cycle, there are more and more files to get compacted for each partition. This leads to a lot of deduplication work that makes the situation worse. Her are the numbers:

**This chart shows:**
1. More files per partition/sequencer for later cycle2. 
5. The cycle takes longer and longer to finish
![Screen Shot 2022-05-12 at 3 13 11 PM](https://user-images.githubusercontent.com/20850014/168153812-937691af-05f9-4c17-9b56-abbc5218b962.png)

**This charts is similar to the one above but shows the file size to get compacted per sequencer**
![Screen Shot 2022-05-12 at 3 16 25 PM](https://user-images.githubusercontent.com/20850014/168154105-beace22f-1431-4e2d-98e1-ce8d021216b8.png)

**This chars shows input compacted file rate for each sequencer every minute**
![Screen Shot 2022-05-12 at 3 17 06 PM](https://user-images.githubusercontent.com/20850014/168154435-f4a0e792-157e-4506-b9fb-b1be49a66f6a.png)

**Similarly, this chart shows how longer compacted output is created because it takes longer to finish a cycle**
![Screen Shot 2022-05-12 at 3 40 33 PM](https://user-images.githubusercontent.com/20850014/168155741-ae35fe06-d0fc-450b-b9ca-fa37366d0a88.png)

**CPU and Memory Usage is quite low**
![Screen Shot 2022-05-12 at 5 18 00 PM](https://user-images.githubusercontent.com/20850014/168169839-228000d5-213c-4b50-b9a6-7621d7516cee.png)

![Screen Shot 2022-05-12 at 5 18 11 PM](https://user-images.githubusercontent.com/20850014/168169999-f25182bc-a4ec-4c19-8ffe-63436be95b02.png)

# Plan:
1. Make Compactor more parallelism to use more threads/CPU
1. Add more debug info to see how many to-be-compacted files per partition. How long each takes.
6. Collect flame chart performance profile
7. If still slow, 1. add 3 more compactors to see if 4 compactors catch up well with 4 Ingesters - CC @mkmik 

# Useful Catalog SQL
```sql
- num files
select count(*) from parquet_file;
select count(*) from parquet_file where to_delete IS NULL;  -- active files
select count(*) from parquet_file where compaction_level =1;
select count(*) from parquet_file where compaction_level =1 and to_delete IS NULL ;
select count(*) from parquet_file where compaction_level =0;
select count(*) from parquet_file where compaction_level =0  and to_delete IS NULL;

-- Large to small files
select ns.name as namespace, substring(t.name, 1, 20) as table, partition_key, file_size_bytes, compaction_level from parquet_file as pf, partition as p, table_name as t, namespace as ns where pf.partition_id=p.id and  pf.table_id = t.id and t.namespace_id = ns.id and to_delete IS NULL order by file_size_bytes DESC;

-- Time of most recent compacted file
select max(to_timestamp(created_at/1000000000)) from parquet_file where compaction_level = 1 and to_delete IS NULL;

-- Most recent compacted file and size
select to_timestamp(created_at/1000000000), file_size_bytes/1024/1024 as size_in_mb from parquet_file where compaction_level = 1  and to_delete IS NULL order by 1 DESC;

-- Num files of each partition not yet compacted
select substring(t.name, 1, 20) as table_name, partition_key, count(*) file_count, sum(file_size_bytes) as sum_size from parquet_file as pf, partition as p, table_name as t where pf.table_id = t.id and pf.partition_id = p.id and compaction_level = 0 and to_delete is NULL group by table_name, partition_key order by file_count desc;
```
# Other useful commands

### Get Compactor Logs
kubectl --context dex@prod01-eu-central-1-aws -n iox logs statefulset/iox-shared-compactor-0

### Flame chart
kubectl --context dex@prod01-eu-central-1-aws -n iox port-forward iox-shared-compactor-0-0 8080 
http://localhost:8080/debug/pprof/profile?seconds=30

**Comment by alamb** [comment]
@NGA-TRAN  the dashboards seem to show that the compactor's CPU and memory are quite low (like one core). Perhaps it needs to be made more parallel (rather than adding more compactors)?

The way `run_compactor` is written it appears to only compact one file at a time (which matchs the compactor's CPU usage of ~ 1):

https://github.com/influxdata/influxdb_iox/blob/de32b1ca54329511f38ed79481ef35c3a367617d/compactor/src/handler.rs#L158-L211

**Comment by NGA-TRAN** [comment]
@alamb 
Good point. This may be also related to #4101  #4324 . Do you think we should open a different ticket for what you say here? @domodwyer may have some idea for this too

**Comment by NGA-TRAN** [comment]
@alamb 
We actually spawn a thread for each partition candidates which seems many https://github.com/influxdata/influxdb_iox/blob/d807941804b845ab1f9c2814f1fcbb919ab0ae00/compactor/src/handler.rs#L177. I am surprised that the CPU is quite low with that. There is so much unnecessary debug info that prevents me from seeing useful information. I will convert those `debug!` to `trace!`.

**Comment by domodwyer** [comment]
Compactor parallelism is [limited based on the size of the input files][code] it is compacting. It will only processes N input files where the byte size of the input files does not exceed the configured limit.

We can tweak this limit by increasing [`INFLUXDB_IOX_COMPACTION_CONCURRENT_SIZE_BYTES`][flag] to a bigger value, allowing the compactor to work on more files in parallel, but this will also increase the memory usage of the compactor. This might conflict with the work @mkmik is doing to correctly size the compactor resources so you'll have to coordinate to get more RAM when you increase the limit 👍 

---

One random compactor I just checked is hitting the size limit after parallelising only 2 compactions:

```
level=debug msg="reached maximum concurrent compaction size limit" max_size=100000000 used_size=215119993 n_compactions=2 target="compactor::handler" location="compactor/src/handler.rs:193" time=1652438008297676554
```


[code]: https://github.com/influxdata/influxdb_iox/blob/31f3d988aeb357fe3ca5f08bc4edd53adef4aba5/compactor/src/handler.rs#L192-L195
[flag]: https://github.com/influxdata/influxdb_iox/blob/31f3d988aeb357fe3ca5f08bc4edd53adef4aba5/clap_blocks/src/compactor.rs#L36-L46

**Comment by alamb** [comment]
The way the parallelism is done could be improved too -- it now will wait for the longest compaction to finish to find the next batch of candidates. 

It would be cool if the number (or max total memory size) of concurrent compactions was set to some fixed size and we kept that many going in parallel

**Comment by domodwyer** [comment]
That's a good point - it should be pretty easy to implement too. I can tackle when I address the memory usage too if no one beats me to it 👍

**Comment by alamb** [comment]
FYI I was wrong above when I said memory usage was quite low. The current dashboard appears to show the memory usage of compactors is very high (even though there is a single CPU core used)

![Screen Shot 2022-05-13 at 9 27 30 AM](https://user-images.githubusercontent.com/490673/168293979-3cf6ea56-494d-49a7-a13e-10d1af94ca13.png)

I believe @domodwyer  has plans to improve it in https://github.com/influxdata/influxdb_iox/issues/4324

**Comment by NGA-TRAN** [comment]
@alamb , @domodwyer and @mkmik : The CPU and memory usage of Compactor depending on some other factors. It can be very high at first but then for some reasons that I have some suspicions and need to investigate more, it slow down and reduce both CPU and memory.

**Comment by alamb** [comment]
the "use a lot of CPU but then drop to one" can be explained by https://github.com/influxdata/influxdb_iox/issues/4585#issuecomment-1125425885

**Comment by alamb** [comment]
Also, I can't say there is huge evidence to support this yet, but I have not so secret hopes to improve sorting in general in DataFusion: https://github.com/apache/arrow-datafusion/issues/2427

**Comment by NGA-TRAN** [comment]
Close this as there are no longer panics and compactors are running well. Will track other optimization in the main #3904

**Comment by NGA-TRAN** [comment]
Let us close this because it is a checklist of old issues. I have move the recent issue out. It is tracked by @jacobmarble 's [dashboard](https://github.com/orgs/influxdata/projects/55/views/35)
