### ISSUE TITLE
Ingest / Ingester Stabilization

### ISSUE THREAD

**Issue by alamb** [influxdata/influxdb_iox#4658]
This is a tracking ticket for issues known to be needed to stabilize the ingester on Influx Cloud

Stabilization in this case basically means:
1. No `panic`s
2. No OOMs
3. Can keep up with production ingest and query load

- [x] https://github.com/influxdata/conductor/issues/1000 
- [x] https://github.com/influxdata/conductor/issues/971
- [x] #4886
- [x] https://github.com/influxdata/influxdb_iox/issues/4621
- [x] https://github.com/influxdata/influxdb_iox/issues/4936
- [x] https://github.com/influxdata/conductor/issues/988
- [ ] #4928
- [x] https://github.com/influxdata/conductor/issues/981
- [x] #4840
- [x] https://github.com/influxdata/influxdb_iox/issues/4789
- [x] https://github.com/influxdata/influxdb_iox/issues/4624
- [x] https://github.com/influxdata/influxdb_iox/issues/4657
- [x] https://github.com/influxdata/conductor/issues/970
- [x] https://github.com/influxdata/conductor/issues/980
- [x] https://github.com/influxdata/influxdb_iox/issues/4567
- [x] https://github.com/influxdata/influxdb_iox/issues/4849
- [x] https://github.com/influxdata/influxdb_iox/issues/5000
- [x] https://github.com/influxdata/conductor/issues/1016
- [x] https://github.com/influxdata/conductor/issues/1017

Related infrastructure, not necessarily ingester:
- [x] https://github.com/influxdata/conductor/issues/989
- [ ] https://github.com/influxdata/influxdb_iox/issues/4895
- [x] https://github.com/influxdata/conductor/issues/987
- [x] https://github.com/influxdata/influxdb_iox/issues/4896

**Comment by alamb** [comment]
June 2022 OOM post mortem analysis https://docs.google.com/document/d/1ngvRw3v-Jz4WNE1waBTpJS32-cFNmMHa0hmhEerT1cY/edit#

**Comment by alamb** [comment]
For the time being I am taking the lead on ingester stabilization so assigning myself

**Comment by alamb** [comment]
Makes sense -- I only now saw 
<img width="737" alt="Screen Shot 2022-06-29 at 6 35 10 AM" src="https://user-images.githubusercontent.com/490673/176449684-568ef89e-c778-437c-a7c6-fff561a5279c.png">

**Comment by alamb** [comment]
Per the call today this is going on the back burner: https://influxdata.slack.com/archives/CRK9M8L5Q/p1657812384568659?thread_ts=1657739394.189219&cid=CRK9M8L5Q
