### ISSUE TITLE
Productionize Deletes / Tombstones

### ISSUE THREAD

**Issue by alamb** [influxdata/influxdb_iox#4690]
As we switched from the "OG" architecture to the "NG" architecture in early 2022, deletes have been partially implemented but not as robustly as the read path. This ticket / epic tracks work needed to make them ready for production

# Required
This list contains things that we think are necessary
- [ ] End to end test for deletes via /api/v2/delete
- [ ] https://github.com/influxdata/influxdb_iox/issues/3582

# Maybe Required
This list contains things that might be necessary
- [ ] https://github.com/influxdata/influxdb_iox/issues/4527
