### ISSUE TITLE
Reduce set of logical types

### ISSUE THREAD

**Issue by e-dard** [influxdata/influxdb_iox#501]
In terms of numeric types we want to initially support the following logical types:

- i64
- u64
- f64

The fixed-width encodings I added to the segment store allow IOx to automatically store columnar data with the above logical types using a smaller physical type if the range of values in the column allows. We can map the following:

- i64: {i64, i32, u32, i16, u16, i8, u8}
- u64: {u64, u32, u16, u8}
- f64: {f64}

We won't store `f64` columns with as single-precision representations because that's lossy.

Right now the Segment Store went a little overboard and supports more logical types than necessary. So I need to clean this up, which will reduce the amount of pattern matching everywhere and make things a bit simpler to work with.

### TODO

- [ ] Remove `i32`, `i16`, `i8`, `u32`, `u16`, `u8` physical types.
- [ ] Remove `f32` physical type.
- [ ] Restrict `Value::Scalar` type to `i64`, `u64`, `f64`.

**Comment by alamb** [comment]
@e-dard  -- does

>  Remove i32, i16, i8, u32, u16, u8 physical types.

Is that meant to be remove `..logical types...` rather than physical types? it seems like those physical types are still useful
