### ISSUE TITLE
Compact a partition

### ISSUE THREAD

**Issue by NGA-TRAN** [influxdata/influxdb_iox#5106]
# Rationale

Design the details and implement `With the partition we’re going to compact` in the [Compaction Strategy & Algorithm](https://docs.google.com/document/d/1G4B0YlXyfBx6A_GLXM7FKneu_NE-TuHKkRovpa_XIaI/edit#heading=h.cpiu6bk26nwq) 

# Subtasks

- [x] https://github.com/influxdata/influxdb_iox/issues/5119
- [x] https://github.com/influxdata/influxdb_iox/issues/5118
- [x] https://github.com/influxdata/influxdb_iox/issues/5120
- [x] influxdata/influxdb_iox#5174
- [x] https://github.com/influxdata/influxdb_iox/issues/5121
- [x] https://github.com/influxdata/influxdb_iox/issues/5123
- [ ] influxdata/influxdb_iox#5172
- [x] influxdata/conductor#1078

**Comment by NGA-TRAN** [comment]
Let us close this because delete is not in our near todo
