### ISSUE TITLE
EPIC: Implement InfluxQL Query Processor

### ISSUE THREAD

**Issue by stuartcarnie** [influxdata/influxdb_iox#5902]
With #5353 complete, the next step in the _InfluxQL for IOx_ journey is to teach IOx how to process an InfluxQL query request.

## Overview

Upon completion of this epic, IOx will be able to 

- [ ] receive an InfluxQL query request from the IOx `influxdb_iox query` command;
- [ ] process the request; and
- [ ] return the results to the client

In order to accomplish this, IOx will require changes in 3 high-level areas:

* Enhancing the `iox_query` crate to process InfluxQL requests, which includes changes to
   * Flight RPC interfaces to handle SQL and InfluxQL queries;
   * parsing and transforming InfluxQL queries so they may be processed by DataFusion; and
   * streaming the response to the client
* The CLI `influxdb_iox query` will require an argument to override the query language
    * [An existing branch](https://github.com/influxdata/influxdb_iox/blob/be1bee06e068fc70bba5b512ee8453b347845d54/influxdb_iox/src/commands/query.rs#L35-L37) demonstrates this for executing `sqlparser-rs` ASTs:

    ```sh
    influxdb_iox query -q ast company_sensors '{"Query":{"with":null,"body":{"Select":{"distinct":false,"top":null,"projection":["Wildcard"],"into":null,"from":[{"relation":{"Table":{"name":[{"value":"cpu","quote_style":null}],"alias":null,"args":null,"with_hints":[]}},"joins":[]}],"lateral_views":[],"selection":null,"group_by":[],"cluster_by":[],"distribute_by":[],"sort_by":[],"having":null,"qualify":null}},"order_by":[],"limit":{"Value":{"Number":["10",false]}},"offset":null,"fetch":null,"lock":null}}'
    ```

**Comment by alamb** [comment]
> The CLI influxdb_iox query will require an argument to override the query language

Makes sense -- that particular command uses the grpc flight API to send SQL and return `RecordBatch`s -- I remember there was talk about having a http `/v1/query` type API as well.

I don't think there is any issue with adding InfluxQL as an option to the grpc flight API, I just wanted to point that out
