### ISSUE TITLE
Design replacement IOx FlightRPC service with FlightSQL service

### ISSUE THREAD

**Issue by stuartcarnie** [influxdata/influxdb_iox#6102]
# Use Case

We would like to expand the tools available to our customers to execute queries using IOx. In particular, we would like IOx to support the [JDBC and ODBC drivers](https://arrow.apache.org/blog/2022/11/01/arrow-flight-sql-jdbc/), which are standard APIs for communicating with database servers. These drivers utilise the [FlightSQL](https://arrow.apache.org/blog/2022/02/16/introducing-arrow-flight-sql/) interface to interface with the database server.

# Proposal

Teach IOx the [FlightSQL](https://arrow.apache.org/blog/2022/02/16/introducing-arrow-flight-sql/) RPC API. We propose two phases:

- [ ] Phase 1: MVP FlightSQL implementation to supersede Flight
- [ ] Phase 2: Complete FlightSQL implementation to support JDBC and ODBC drivers[^1]

[^1]: Details to be expanded in a future issue

## Phase 1: MVP FlightSQL

This phase should implement the minimal FlightSQL RPC in order to execute SQL and InfluxQL statements from our existing services and clients. It should supersede the existing Flight implementation, such that existing clients of IOx may be updated with minimal effort, and continue to function.

### Existing Flight RPC

The current Flight interface communication and data flow is as follows:

```mermaid
sequenceDiagram
participant c as client
participant s as IOx

c->>+s: DoGet(Ticket)
s->>-c: return Arrow results
```

A Flight `Ticket` is a sequence of bytes that is understood by a specific implementation. In the case of IOx, this is a serialised [protobuf message](https://github.com/influxdata/influxdb_iox/blob/106d3a76ded657ddc36d22c0ad433fc705ecd5aa/generated_types/protos/influxdata/iox/querier/v1/flight.proto#L5-L12):

```rust
// Request body for ticket in "end-user to querier" flight requests.
message ReadInfo {
  // Namespace(/database) name.
  string namespace_name = 1;


  // SQL query.
  string sql_query = 2;
}
```

IOx clients currently execute queries directly using the `DoGet` API, and must be aware of the `Ticket` format. As is suggested by the [Flight announcement post](https://arrow.apache.org/blog/2019/10/13/introducing-arrow-flight/), clients would call the `GetFlightInfo` API with an IOx-specific command object, and in return, the IOx server would respond with `FlightInfo` that encodes a list of end points and `Ticket`s to execute the queries. This is essentially how FlightSQL works, except _IOx-specific command_ is replaced with well-known commands, such as `CommandStatementQuery`.

### Minimal FlightSQL implementation

To reduce the development time, the IOx FlightSQL API can be developed incrementally. As described in the FlightSQL announcement post, the flow of requests for a FlightSQL command to execute a SQL query are as follows:

```mermaid
sequenceDiagram
participant c as client
participant s as IOx

c->>s: GetFlightInfo(CommandStatementQuery)
s->>c: FlightInfo{..., Ticket, ...}
c->>+s: DoGet(Ticket)
s->>-c: return Arrow results
```

Therefore, we propose IOx initially support the `CommandStatementQuery` FlightSQL command.

The `arrow-rs` crate provides a base implementation, therefore the high-level steps are

- [ ] Update existing [Flight service](https://github.com/influxdata/influxdb_iox/blob/106d3a76ded657ddc36d22c0ad433fc705ecd5aa/service_grpc_flight/src/lib.rs#L207) to use the [FlightSQL service](https://github.com/apache/arrow-rs/blob/master/arrow-flight/src/sql/server.rs)
    - See [an example](https://github.com/apache/arrow-ballista/blob/926605e7a135fb74016392cedf94be519c9ba5c1/ballista/scheduler/src/flight_sql.rs#L483) in the Ballista repo

- [ ] Implement the `get_flight_info_statement` API to return a `FlightInfo` that encodes a `Ticket` to execute a query.
    - [ ] See [this example](https://github.com/apache/arrow-ballista/blob/926605e7a135fb74016392cedf94be519c9ba5c1/ballista/scheduler/src/flight_sql.rs#L613) in the Ballista repo
    
- [ ] Implement query execution via `do_get`, either
    - [ ] via the `do_get_fallback` API to execute the query and return record batches
        - [ ] See [this example](https://github.com/apache/arrow-ballista/blob/926605e7a135fb74016392cedf94be519c9ba5c1/ballista/scheduler/src/flight_sql.rs#L545) in the Ballista repo
    - [ ] OR using the existing `TicketStatementQuery` message

### Metadata

FlightSQL provides access to the gRPC request, which in turn provides access to the gRPC `metadata` via an accessor, such as in this example for Ballista:

https://github.com/apache/arrow-ballista/blob/926605e7a135fb74016392cedf94be519c9ba5c1/ballista/scheduler/src/flight_sql.rs#LL150

Metadata is arbitrary key / value pairs, which is an ideal candidate for encoding context that IOx may require.

#### Namespaces

IOx FlightSQL requests must identify the target namespace for the query. Given the `CommandStatementQuery` command does not provide additional fields to encode this context, therefore it is recommended that namespace is specified as a key / value pair via gRPC metadata. 

#### Query Language

The `CommandStatementQuery` command does not provide additional fields to encode this context. It is recommended that an optional key is interrogated to determine the query language. When omitted, it is assumed that the language is SQL. 

### `do_get` implementation

The `get_flight_info` API returns a `FlightInfo` response that directs the client to the `do_get` API for processing the query request and returning the record batches. The `arrow-rs` FlightSQL service provides two customisation points.

#### TicketStatementQuery message

The `get_flight_info` should encode a ticket using the `TicketStatementQuery` message, which will be handled in the `do_get` function and call the `do_get_statement`:

https://github.com/apache/arrow-rs/blob/fe3318bba24abfe572fa037a0b8805a15bdf5c45/arrow-flight/src/sql/server.rs#L423-L425

The `do_get_statement` is implemented by IOx. The `TicketStatementQuery` message provides a bytes field to encode data representing the query:

https://github.com/apache/arrow/blob/5182d62f86bd45aee3a3eb6b7ac891c40ca50c88/format/FlightSql.proto#L1724-L1729

IOx could encode a ticket describing how `do_get` should execute the command. An example of a ticket is the `ReadInfo` message in the existing IOx Flight implementation:

https://github.com/influxdata/influxdb_iox/blob/106d3a76ded657ddc36d22c0ad433fc705ecd5aa/generated_types/protos/influxdata/iox/querier/v1/flight.proto#L5-L12

See the **Multiple Query Languages** section later in this document for the proposed ticket format for FlightSQL.

#### Custom message

The second approach is to encode a custom command message, which would be handled by the `do_get_fallback` API:

https://github.com/apache/arrow-rs/blob/fe3318bba24abfe572fa037a0b8805a15bdf5c45/arrow-flight/src/sql/server.rs#L457

This is the approach taken by Ballista, encoding [an `Action`](https://github.com/apache/arrow-ballista/blob/926605e7a135fb74016392cedf94be519c9ba5c1/ballista/scheduler/src/flight_sql.rs#L545-L549) message. Once again, see the **Multiple Query Languages** section later in this document for the proposed ticket format

### InfluxQL support

The base FlightSQL service in the `arrow-rs` repository has limited customisation points. The original announcement for the Flight API indicates the best practice approach would be to use the `get_flight_info` request with a custom command, such as `CommandStatementInfluxQLQuery`:

```mermaid
sequenceDiagram
participant c as client
participant s as IOx

c->>s: GetFlightInfo(CommandStatementInfluxQLQuery)
s->>c: FlightInfo{..., Ticket, ...}
c->>+s: DoGet(Ticket)
s->>-c: return Arrow results
```

This will require updating the `arrow-rs` implementation to provide a fallback API here:

https://github.com/apache/arrow-rs/blob/fe3318bba24abfe572fa037a0b8805a15bdf5c45/arrow-flight/src/sql/server.rs#L397-L400

similar to the `do_get` API:

https://github.com/apache/arrow-rs/blob/fe3318bba24abfe572fa037a0b8805a15bdf5c45/arrow-flight/src/sql/server.rs#L457

### Multiple query languages

For FlightSQL, the `do_get` API will receive a _ticket_, which is an encoded command, generated from the `get_flight_info` API.  `get_flight_info` is responsible for generating this ticket, and will eventually generate tickets to execute SQL and InfluxQL queries and potentially other languages in the future.

To future-proof `do_get`, it should receive commands encoded using the [`Any`](https://docs.rs/prost-types/latest/prost_types/struct.Any.html) type. The `Any` type is a standardised approach to serialising *typed* protobuf messages. The `Any` type encodes two fields, first a URI to identify the protobuf type, followed by a vector of bytes representing the serialised message. The `arrow-rs` FlightSQL service uses this approach to encode the many commands understood by the `get_flight_info` API:

https://github.com/apache/arrow-rs/blob/8d75101e3773e5d74c8d5cda356a9eaba34acf90/arrow-flight/src/sql/server.rs#L314-L315

The [`ProstAnyExt`](https://github.com/apache/arrow-rs/blob/8d75101e3773e5d74c8d5cda356a9eaba34acf90/arrow-flight/src/sql/mod.rs#L113-L129) trait defines an API to test whether the `Any` type is a particular message via the [`is`](https://github.com/apache/arrow-rs/blob/8d75101e3773e5d74c8d5cda356a9eaba34acf90/arrow-flight/src/sql/mod.rs#L116-L117) API. Usage of this trait can be observed in the [`get_flight_info`](https://github.com/apache/arrow-rs/blob/8d75101e3773e5d74c8d5cda356a9eaba34acf90/arrow-flight/src/sql/server.rs#L317) implementation via the `is` function.

By using `Any`, the behaviour of `do_get` can handle commands to execute SQL, InfluxQL or even a DataFusion `LogicalPlan`[^logical_plan].

[^logical_plan]: If tickets were always logical plans, `do_get` wouldn't need to distinguish which query language it is executing.

### Backwards Compatibility

Given IOx is deployed in beta, the team must decide if the `do_get` API must ensure backwards compatibility with existing clients. If required, we present two options.

- [ ] **TODO**: Decide if backwards compatibility is required and if so, which approach to implement

#### Option 1: Extend Flight service on port 8081

Extend the existing service to try deserialising tickets in order of priority. This is already the case with `do_get`, which first tries to decode the `ReadInfo` message as a protocol buffer, followed by a JSON:

https://github.com/influxdata/influxdb_iox/blob/106d3a76ded657ddc36d22c0ad433fc705ecd5aa/service_grpc_flight/src/lib.rs#L235-L239

#### Option 2: Add FlightSQL to new port

This is a clean break, and involves adding a new flight_sql crate and starting a FlightSQL service on a new port. The existing Flight service will remain unmodified and eventually removed once FlightSQL is rolled out.

**Comment by stuartcarnie** [comment]
cc/ @alamb / @jacobmarble

**Comment by alamb** [comment]
@avantgardnerio FYI we are preparing to implement FlightSQL in IOx. 

If you have any thoughts / suggestions on what parts of the Ballista implementation make sense to help refactor and bring upstream into arrow-flight we would love to hear them. 

Also, do you know if there is anyone else who worked on the FlightSQL project in Ballista we should ask?

**Comment by avantgardnerio** [comment]
> if there is anyone else

AFAIK, it's all been me. I'm happy to answer any questions though. There is definitely a bunch of helper functions near the top of `flight_sql.rs` that can be brought up into `arrow-rs`, but for the most part creating a FlightSQL server is just implementing `FlightSqlService`.

I will say one extremely painful aspect of having FlightSQL in `arrow-rs` is long release times to get a change from arrow, to datafusion, to Ballista (and now IOx). I have to continually rebase a change for months before it gets into a versioned release, so anything we do move down to `arrow-rs` should really be specced out well. 

My previous strategy was to do the absolute minimum there and just pass everything up to the implementer.

**Comment by stuartcarnie** [comment]
Thanks @avantgardnerio.

First question is regarding customising the `get_flight_info` request, which currently does handle custom command messages:

https://github.com/apache/arrow-rs/blob/e4e15f8e7efc31db6469198852c3e7719577411d/arrow-flight/src/sql/server.rs#L397-L400

Would you object to a `get_flight_info_fallback`, similar to the `do_get_fallback`:

https://github.com/apache/arrow-rs/blob/e4e15f8e7efc31db6469198852c3e7719577411d/arrow-flight/src/sql/server.rs#L457

We are considering handling a custom `CommandStatementInfluxQLQuery` in this API.

**Comment by avantgardnerio** [comment]
> Would you object

Not at all, though if you are extending that - are you really FlightSQL protocol compatible?

**Comment by avantgardnerio** [comment]
FWIW, I think one of the first things that will be required for a "proper" implementation is the long-missing FlightSQL Rust Client. One of our developers started work on it [here](https://github.com/spaceandtimelabs/arrow-rs/tree/bg_help_dhamo) but I don't think he got very far before getting pulled away. If I recall, the branch does at least have a failing test and show where to start.

Finishing that is currently my highest priority after JDBC integration with our main product, but that might not be until December/January.

**Comment by jacobmarble** [comment]
> Option 2: Add FlightSQL to new port

I favor this approach because it's simpler, and allows us to rethink any details in the current implementation.

> use the get_flight_info request with a custom command, such as CommandStatementInfluxQLQuery

Does this not imply that a custom client would be necessary to issue InfluxQL queries to the service?

If so, I would rather stick with `CommandStatementQuery`, and provide a way for any client to use InfluxQL. Two alternatives:
- IOx query parser handles `SET LANG=influxql`
- handle `lang=influxql` in client-configurable settings:
    - FlightSQL gRPC request metadata
    - PostgreSQL FEBE startup message parameters

**Comment by stuartcarnie** [comment]
> > use the get_flight_info request with a custom command, such as CommandStatementInfluxQLQuery
> 
> Does this not imply that a custom client would be necessary to issue InfluxQL queries to the service?
> 

Yes, though FlightSQL is a superset of Flight, therefore we're adding a command to the Flight API and not FlightSQL. An existing Flight client should only require minimal changes to support this additional InfluxQL command.

InfluxQL clients will be able to use the `/query` HTTP end point for Cloud 2 and IOx will eventually speak the v1 HTTP API natively for OSS installations and any future products.

My hesitance for adding InfluxQL is due to my current understanding that FlightSQL is intended for building an API for executing ANSI SQL and its derivatives. InfluxQL looks a lot like SQL, but it definitely isn't SQL. There are a number of constants for the `CommandSqlInfo` FlightSQL command to indicate which what level of ANSI SQL is supported:

https://github.com/apache/arrow-rs/blob/430eb84d0d64b15e2f8b13dfa0f3bd014d3e50c9/format/FlightSql.proto#L288-L324

> If so, I would rather stick with `CommandStatementQuery` and `TicketStatementQuery`, and provide a way for any client to use InfluxQL. Two alternatives:
> 
> * IOx query parser handles `SET LANG=influxql`
> * handle `lang=influxql` in client-configurable settings:
>   
>   * FlightSQL: gRPC `CommandStatementQuery` request metadata
>   * PostgreSQL FEBE startup message parameters

I think this could work, but the downside is that tools that use the JDBC driver, like DataGrip, or other IntelliJ IDEs won't know about InfluxQL or these flags and therefore autocompletion and other IDE experiences will be awkward or surprising.

Adding a new command would be very easy and seems to be the correct approach, in the spirit of Apache Flight and Apache FlightSQL.

I am not 100% opposed to it, just highlighting the potential downsides before we commit.

**Comment by stuartcarnie** [comment]
Had a brief discussion with Brent on the Apache Slack forums, and he didn't seem to think it was an issue.

Fortunately, IntelliJ supports dialects, so we could conceivably add an InfluxQL dialect in the future

**Comment by stuartcarnie** [comment]
Ultimately, my goal is that we can build great user experiences. IntelliJ does provide ways of doing this.

**Comment by stuartcarnie** [comment]
@jacobmarble it occurred to me that I had not identified how FlightSQL would determine the target namespace as most FlightSQL command requests, such as `CommandStatementQuery`, do not provide a mechanism for encoding arbitrary key / value data.

I did some additional digging and (as I believe you have also determined) we can use gRPC metadata for this. I have added the following to the main issue:

### Metadata

FlightSQL provides access to the gRPC request, which in turn provides access to the gRPC `metadata` via an accessor, such as in this example for Ballista:

https://github.com/apache/arrow-ballista/blob/926605e7a135fb74016392cedf94be519c9ba5c1/ballista/scheduler/src/flight_sql.rs#LL150

Metadata is arbitrary key / value pairs, which is an ideal candidate for encoding context that IOx may require.

#### Namespaces

IOx FlightSQL requests must identify the target namespace for the query. Given the `CommandStatementQuery` command does not provide additional fields to encode this context, it is therefore recommended that the `namespace` is specified as a key / value pair via gRPC metadata. 

#### Query Language

The `CommandStatementQuery` command does not provide additional fields to encode this context. It is recommended that an optional key is interrogated to determine the query language. When omitted, it is assumed that the language is SQL.

**Comment by stuartcarnie** [comment]
To make sure I was on the right track, I wanted to validate I could send arbitrary headers and read them in IOx.

1.  Modified the `influxdb_iox query` command here:

https://github.com/influxdata/influxdb_iox/blob/bdff4e88487717018490d10feabc8239f6357f94/influxdb_iox/src/main.rs#LL243

To add an arbitrary header into the gRPC connection:

```rust
builder = builder.header(
    http::header::HeaderName::from_str("IOX_NAMESPACE").unwrap(),
    http::header::HeaderValue::from_str("test_namespace").unwrap(),
);
```

2. Extracted the header in `do_get` above here:

https://github.com/influxdata/influxdb_iox/blob/51afe53d23ac9a4b728595041c4230bed65a2d4e/service_grpc_flight/src/lib.rs#L222

```rust
let ns = request.borrow().metadata().get("IOX_NAMESPACE");
if let Some(ns) = ns {
    info!(?ns, "Have metadata");
}
```

Which printed the following log line 🥳 

```text
2022-11-14T05:33:43.946460Z  INFO service_grpc_flight: Have metadata ns="test_namespace"
```

**Comment by mkmik** [comment]
FYI currently you can't set arbitrary trailers with tonic

**Comment by stuartcarnie** [comment]
@mkmik that's unfortunate, as trailers are a good way to send statistics. I implemented this for `storage` (values, bytes scanned) → `influxqld` → `gatewayd`, and `gatewayd` logged the query, along with all the stats.

**Comment by mkmik** [comment]
Yes that's how I discovered this. Anyway we can help by implementing this feature upstream

**Comment by stuartcarnie** [comment]
> Anyway we can help by implementing this feature upstream

Sounds like a plan!

**Comment by alamb** [comment]
A fun weekend coding project perhaps

**Comment by avantgardnerio** [comment]
FWIW @stuartcarnie and @alamb I have a working FlightSQL client (based off @wangfenjin's work). https://gist.github.com/avantgardnerio/be60da17b21396c4540fe5d16c1cd37b Happy to PR it back to arrow-rs if that helps you guys.

**Comment by alamb** [comment]
@avantgardnerio -- I would love to have a working flight SQL client in `arrow-rs` -- thank you! cc @tustvold

**Comment by avantgardnerio** [comment]
PR is here https://github.com/apache/arrow-rs/pull/3207

**Comment by alamb** [comment]
Regarding targeting a specific IOx namespace (e.g. @stuartcarnie 's comment https://github.com/influxdata/influxdb_iox/issues/6102#issuecomment-1312915756)

Most other databases I know of encode the equivalent of namespace (e.g. 'database') in the URL (e.g. `postgres://localhost/alamb` maps to the `alamb` database)

So perhaps we could use the same scheme:

`http://iox-querier/my_namespace` would run queries against the `my_namespace` url

I need to figure out if this is possible

**Comment by alamb** [comment]
Basically @stuartcarnie  has layed out a great plan and I propose to more or less follow it.


# Solution Sketch (Phase 1):
1. Extend IOx so that talks both FlightSQL as well as the existing IOx Flight API on port 8082.
2. To target a certain namespace a different URL will be used: `http://iox-querier:8082/flightsql/my_namespace`


# Solution Sketch (Phase 2):
1. Port existing IOx Flight clients to use FlightSQL
2. Remove IOx Flight API (potentially)
3. Fill out FlightSQL support (prepared statements, etc) so that it works with the FlightSQL JDBC / ODBC drivers.


# Anticpated benefits of this approach:
1. Rollout incrementally  without outages (deprecate old clients / pigox, migrate them to flight SQL)
2. Natural place for InfluxQL extension to live (as InfluxQL is not part of FlightSQL, we will need to extend it somehow)
3. IOx should be positioned to "just work" with existing FlightSQL ecosystem






# More details:


## Open questions:
1. Is it technically possible to retain backwards compatibility? A: I will make a technical spike to find out
2. How will we tell which IOx namespace is targeted? A: I will try to encode the namespace in the url: `http://iox-querier:8082/flightsql/namespace` 
1. How does this effect Pigox and queryrouterd (which already handles Flight SQL?)?
2. Is there a golang client for FlightSQL? A: yes https://github.com/apache/arrow/tree/master/go/arrow/flight/flightsql
2. What are the implications for querier <--> ingester communication (which also uses the existing Flight service)? A: As long as this protocol is backwards compatible,ther are  no implications.

## Testing needed
1. tests in the influxdb_iox repo (needs a Rust FlightSQL, which conveniently @avantgardnerio has contributed https://github.com/apache/arrow-rs/pull/3207)
2. Coverage for backwards compatibility (existing tests probably cover this)
1. Integration test coverage (with the C++ flight SQL client, then maybe with some basic JDBC and ODBC CLI)


# Needed help:
I will likely need help with the golang parts (pigox and queryrouterd). Hopefully we can pull off the backwards compatibility story and then this can be incrementally rolled out.

**Comment by alamb** [comment]
I plan to do a technical spike to make sure it is possible to make a backwards compatible endpoint and use URL to specify namespace

**Comment by tustvold** [comment]
It might be easier to use an HTTP header than URL path, grpc is fairly proscriptive about path construction, and so even if you can get tonic to play ball, other gRPC libraries may not be so accommodating.

I think tonic exposes headers as https://docs.rs/tonic/latest/tonic/metadata/struct.MetadataMap.html

**Comment by avantgardnerio** [comment]
> postgres://localhost/alamb

Sorry, I'm only tangentally following, but the FlightSQL JDBC driver will expect it to be in the form of `jdbc:arrow-flight://127.0.0.1:1234` as it's all the same protocol.

The driver tries to list catalogs, so you could use that + permissions based on the authentication to determine what databases folks can see. Aside from those options I agree with @tustvold : gRPC metadata seems like the most reliable way to get extra information through without altering the FlightSQL protocol itself.

**Comment by alamb** [comment]
thanks @tustvold  and @avantgardnerio  -- I'll see what I can come up with when playing with the jdbc driver

**Comment by alamb** [comment]
Regarding namespace (catalog) support, @avantgardnerio  reminded me of a thread on the arrow dev mailing list where they are discussing adding support to FlightSQL

https://lists.apache.org/thread/fd6r1n7vt91sg2c7fr35wcrsqz6x4645

I think the solutions they are proposing will map quite nicely to our notion of namespaces.

So I think initially if we need to specify namespaces via a header while we wait for proper support to be finalized in FlightSQL itself, that will work out well

**Comment by alamb** [comment]
I think this ticket has served us well as a "come up with a design for FlightSQL" -- I have filed https://github.com/influxdata/influxdb_iox/issues/6390 to track the implementation and I am claiming this task is complete

Thank you to all who were involved!
