### ISSUE TITLE
FlightSQL Milestone 2: Support basic ad hoc queries

### ISSUE THREAD

**Issue by alamb** [influxdata/influxdb_iox#6411]
It has three main parts:
- [ ]  Create a general Flight client by generalizing some of the clever code in the existing IOx Flight Client
- [ ]  Build a FlightSQL client on top of that client
- [ ]  Implement the server side of that

I think once I have the client part sorted out, building the server side will be straightforward and mechanical.

I intend to propose upstreaming the general flight client and the FightSQL client to the `arrow-filight` crate

In terms of a project plan, I hope to  have a PR up with this approach working in the next day or two, but then it will likely take me another ~ 5 working days to get it pieced up into PRs (with testing, documentation, etc)
