### ISSUE TITLE
Refcount WAL segments for correctness

### ISSUE THREAD

**Issue by domodwyer** [influxdata/influxdb_iox#6566]
We should only drop a WAL segment once we know definitively that all the data within that segment has been persisted.

Since https://github.com/influxdata/influxdb_iox/pull/6537, we now know which sequence numbers were in which persisted data buffers. This allows us to track what has, and has not been uploaded within a WAL file, and drop the WAL once all sequence numbers within a segment have been observed as persisted.
```[tasklist]
### Tasks
- [ ] https://github.com/influxdata/influxdb_iox/issues/7955
- [ ] https://github.com/influxdata/influxdb_iox/issues/7260
- [x] Replace op level `sequence_number` field from the WAL with the per-partition sequence number table
- [x] Assign unique `SequenceNumber` per-partition in each write
- [ ] Hook up WAL reference counting code to the per-partition sequence number
```
