### ISSUE TITLE
InfluxQL-IOx: Teach planner how to process gap-filling `FILL` clause

### ISSUE THREAD

**Issue by stuartcarnie** [influxdata/influxdb_iox#6916]
Teach the InfluxQL planner how to generate a logical plan to process the `FILL` clause and perform gap filling.

```[tasklist]
- [x] `FILL(null)` **default** via #7359
- [x] `FILL(linear)` via #7466
- [x] `FILL(previous)` via #7359
- [x] `FILL(<numeric value>)` via #7359
```

# Prerequisites

- #6594
- #6915

# Background

The `FILL(fill_option)` clause is used in conjunction with the `GROUP BY TIME` clause to configure how intervals are handled when there are no associated points within a time window. When the `FILL` clause is omitted, the default behaviour when grouping by time is `FILL(null)`, which is to return `NULL` values for intervals without corresponding points.

The possible values for `fill_option` are:

| Option         | Description                                                 |
|:---------------|:------------------------------------------------------------|
| `null`         | Return null value                                           |
| `none`         | Skip the window                                             |
| `previous`     | Use the value from the previous interval                    |
| `linear`       | Interpolate from the previous value using a linear function |
| literal number | Use the literal number                                      |

## Time range

When gap filling, it is necessary that the lower and upper bounds of the time range. The rules are as follows.

### Lower bound

* Does `WHERE` clause contains a `time` range predicate?
  * Can a lower bound be resolved to a scalar value?
* If no lower bounds can be determined, it is determined by the first point

### Upper bound

* Does `WHERE` clause contains a `time` range predicate?
  * Can a upper bound be resolved to a scalar value?
* If no upper bounds can be determined, set to `now()`:

  https://github.com/influxdata/influxdb/blob/98361e207349a3643bcc332d54b009818fe7585f/query/compile.go#L172-L176

**Comment by wolffcm** [comment]
Hi @stuart, I am wondering about how the InfluxQL planner will work with my gap filling work. I can see two approaches:
- The InfluxQL planner constructs a logical `GapFill` node directly:
https://github.com/influxdata/influxdb_iox/blob/18e183a54b8bc99672a8939ccd779e3fc1276edb/iox_query/src/exec/gapfill.rs#L33-L55
- Or it might instead construct an `Aggregate` logical node where the `time` group column is wrapped in a call to `DATE_BIN_GAPFILL`, and then the DF logical planner could use the `HandleGapFill` rule instead: https://github.com/influxdata/influxdb_iox/blob/18e183a54b8bc99672a8939ccd779e3fc1276edb/iox_query/src/logical_optimizer/handle_gapfill.rs#L63

I had been thinking that you would take the first approach. As a result of this assumption on my part, I have been focusing more on the physical implementation but not the planner so much.

But it occurs to me that maybe the second approach is feasible. One thing to tease out would be that the TimeScale behavior for gap filling requires a lower bound in the WHERE clause, but InfluxQL does not---in absence of predicates InfluxQL assumes the lower bound is the first point in the series, and that the upper bound is `now()`. So `HandleGapFill` would need to be made more general.

Another minor concern is that `HandleGapFill` traverses its input looking for a `Filter` to discover the time range to gap fill. The InfluxQL plan would need to be constructed in such a way that those predicates can be discovered. I am fairly certain that it will, but I thought it was worth mentioning.

Thoughts on this? I am thinking that the InfluxQL planner making use of `HandleGapFill` would help share more code with the SQL planner flow, at the cost of a small amount of complexity. It seems likely worth it to me.

**Comment by stuartcarnie** [comment]
If we can share more code, that makes sense. I have a few questions with using `HandleGapFill`

* How would we specify that the aggregate nodes need to use a specific `FILL` strategy (`null`, `<number>` or `previous`)? 
* When `FILL(none)` is used, presumably we'll construct a logical plan that uses `DATE_BIN` instead.
* How would selectors work, which are more complicated in that they can project aggregate and non-aggregate columns. I discuss that in the following:

  * https://github.com/influxdata/influxdb_iox/issues/6112
  
An example query, which finds the minimum `usage_idle` in each time interval and then selects the associated `usage_system` value at the same timestamp 🤯 

```sql
select min(usage_idle), usage_system from cpu where time >= '2020-06-11T16:52:00Z' AND time < '2020-06-11T17:00:00Z' group by time(30s)
```
```
name: cpu
time                 min               usage_system
----                 ---               ------------
2020-06-11T16:52:00Z 88.6              6.7
2020-06-11T16:52:30Z 83.41708542713567 7.437185929648241
2020-06-11T16:53:00Z 86.91308691308691 6.593406593406593
2020-06-11T16:53:30Z 89.8              5.2
2020-06-11T16:54:00Z 88.82235528942115 5.588822355289421
2020-06-11T16:54:30Z
2020-06-11T16:55:00Z
2020-06-11T16:55:30Z
```

**Comment by wolffcm** [comment]
Thanks for your comments, I'll try to answer your questions.

> - How would we specify that the aggregate nodes need to use a specific FILL strategy (null, <number> or previous)?
>
> - When FILL(none) is used, presumably we'll construct a logical plan that uses DATE_BIN instead.

For reference, I merged #7150 this morning which contains a type for describing fill strategy:
https://github.com/influxdata/influxdb_iox/blob/3f3a47eae9435867084deee28fa5417028677119/iox_query/src/exec/gapfill.rs#L61-L74

I'm realizing now that `FILL(NONE)` is not the same as `FILL(NULL)`, is that right? `NONE` is no gap filling at all I guess. The docs aren't especially helpful here, but I just tried it out and it seems to be the case. I will need to update the comment for `FillStrategy`.

I discussed planning in the gap filling design document:
https://docs.google.com/document/d/1vIcs9uhlCX_AkD9bemcDx-YhBOVe_TW5sBbXtKCHIfk/edit#heading=h.jvs2a04uoxuk

For reference `LOCF` is documented here, it has a parameter called `treat_null_as_missing` which would produce the InfluxQL behavior for `FILL(PREVIOUS)`.
https://docs.timescale.com/api/latest/hyperfunctions/gapfilling-interpolation/locf/#locf-community

---

Some context: on the SQL side, fill strategy is defined by using `LOCF` or `INTERPOLATE` on the SELECT list, but neither of these are implemented yet.

Once those functions exist, `HandleGapFill` will need to have its logic updated:
- Create a `GapFill` node that follows the initial `Aggregate` when `DATE_BIN_GAPFILL` is present in the group columns (this is what it does today already). By default, the aggregate columns will have a fill strategy of `Null`.
- This part still needs to be done: look for a `Project` above the `GapFill` node that contains calls to `LOCF` or `INTERPOLATE` on aggregate columns, and then push them down into the `GapFill` node by updating the `FillStrategy` for the corresponding columns.

---

On the InfluxQL side, I'm thinking that `GROUP BY ..., time(1m)` will lead to generating a logical plan that contains an `Aggregate` node that contains a group column like `DATE_BIN(interval '1 minute', time, ...)`.

From there, I'd imagine we could get the correct behavior out of `HandleGapFill` by proceeding like this:
- When `FILL` is present and the strategy is not `None`, change the call to `DATE_BIN` to `DATE_BIN_GAPFILL` in the `Aggregate` node that the InfluxQL planner creates.
- Then depending on the strategy:
  - `NULL`: This is the default behavior. Nothing needs to happen here.
  - `PREVIOUS`: Create a new `Project` above the `Aggregate` that wraps each aggregate column in `LOCF` with `treat_null_as_missing` set to `true`. `HandleGapFill` will push down `LOCF`, and update the fill strategy.
  - `LINEAR`: Same as above but use `INTERPOLATE` instead of `LOCF`.
  - `<value>`: Create a new `Project` that wraps each aggregate column with `COALESCE(<agg_col>, <value>)`. This should produce the behavior InfluxQL needs. `COALESCE` is a standard SQL function, which DataFusion already supports.

---

> How would selectors work, which are more complicated in that they can project aggregate and non-aggregate columns.

Yes, this is a tricky one. There are UDAFs in the `query_functions` crate that (if I understand right, I believe that @alamb authored them) create struct columns that contain the projected values for this case.

I am thinking that maybe selectors are a concern that is orthogonal to gap filling, provided that the following conditions hold?
- The time input to `GapFill` has bin-aligned values (based on your link I think this is the case)
- There is an aggregate column that can be wrapped as appropriate in a succeeding `Project` node. This column may well have a struct type. (Seems like `INTERPOLATE` would not work here though).

For such queries at some point the struct column will need to be flattened into several columns I guess. It's still unclear to me if this happens before or after gap filling occurs.

**Comment by stuartcarnie** [comment]
Unfortunately, selectors are not intuitive as as they have differing restrictions depending on the query, which I've summarised as follows:

## Single selector queries

A single selector may also be combined with raw fields, to select the field values[^1] for the matching timestamp

```sql
select min(f64), i64, str from m0
```
```
name: m0
time                min  i64 str
----                ---  --- ---
1667181600000000000 10.1 101 hi
```

[^1]: If no value were to exist for any of the raw projected fields, they would produce `null` values.

@alamb do you think it is possible to enhance the selector functions to read additional row values, along with the timestamp and other fields?

## Multiple selector queries

If multiple selectors are projected in the select list, the timestamp is the minimum value of the window

```sql
select min(f64), max(f64) from m0 where time >= '2004-04-09T12:13:14Z'
```
```
name: m0
time                 min  max
----                 ---  ---
2004-04-09T12:13:14Z 10.1 21.2
```
  
> **Note** 
>
> This is no longer a _selector_ query, as the timestamp is lost. It would be considered an aggregate query.

### Restrictions

Combining multiple selectors and fields is not supported

```sql
select min(f64), max(f64), i64, str from m0
```
```
ERR: mixing multiple selector functions with tags or fields is not supported
```

## With `GROUP BY tag, tag..`

Selector queries can group by tags, to produce matching points for each group key.

```sql
select min(f64), i64, str from m0 group by tag0
```
```text
name: m0
tags: tag0=val00
time                 min  i64 str
----                 ---  --- ---
2022-10-31T02:00:00Z 10.1 101 hi

name: m0
tags: tag0=val01
time                 min  i64 str
----                 ---  --- ---
2022-10-31T02:00:00Z 11.3 211 lo

name: m0
tags: tag0=val02
time                 min  i64 str
----                 ---  --- ---
2022-10-31T02:00:00Z 10.4 101 lo
```

## With `GROUP BY TIME()`

Selector queries support windowing and interpolation. For example, the following query will window by 5s intervals and fill any windows missing values with 0:

```sql
SELECT max(f64), i64 from m0 
WHERE time >= '2022-10-31T02:00:00Z' AND time < '2022-10-31T02:01:00Z' 
GROUP BY TIME(5s) 
FILL(0)
```
```text
2022-10-31T02:00:00Z 11.3 211
2022-10-31T02:00:05Z 0    0
2022-10-31T02:00:10Z 21.2 211
2022-10-31T02:00:15Z 0    0
2022-10-31T02:00:20Z 11.2 191
2022-10-31T02:00:25Z 0    0
2022-10-31T02:00:30Z 19.2 392
2022-10-31T02:00:35Z 0    0
2022-10-31T02:00:40Z 0    0
2022-10-31T02:00:45Z 0    0
2022-10-31T02:00:50Z 0    0
2022-10-31T02:00:55Z 0    0
```

**Comment by wolffcm** [comment]
Thanks for the explanation of selectors! I think the only query here that concerns gap filling is the last one, if I understand right.

It might be helpful to look at this example?

```sql
SELECT max(f64), i64 from m0 
WHERE time >= '2022-10-31T02:00:00Z' AND time < '2022-10-31T02:01:00Z' 
GROUP BY TIME(5s) 
FILL(previous)
```
(I changed the `FILL` to `PREVIOUS` from the query above here, since that is a case that `GapFill` has to handle explicitly.)

Let's assume that we _can_ have selectors that can produce multiple values, in this case `max(f64)` would actually produce a struct of `{f64, i64, time}`. It seems possible to me, but I am not certain.

But given that a selector can produce the appropriate struct type, I think it would be possible to get the right behavior with a pseudo-plan like this:
```
GapFill  group_expr=[time_5s], aggr_expr=[locf(max_f64), locf(i64)], params={stride=...}
  Projection  [time_5s, struct_col.f64 as max_f64, struct_col.i64 as i64]
    Aggregate  group_expr=[date_bin(5s, time) as time_5s], aggr_expr=[selector_max(f64) as struct_col]
      ...
```
Here there is an extra projection between `Aggregate` and `GapFill` that flattens the struct. Does that seem right?

The only way I can see `HandleGapFill` producing a plan like this would be if it had some additional logic to handle this case. I am not sure if that is a good idea because it might be confusing if the InfluxQL front end added a flattening projection for other (non-gapfill) queries some of the time, but the planner rule was adding it other times (when gap filling).

**Comment by stuartcarnie** [comment]
@wolffcm, regarding:

> Another minor concern is that HandleGapFill traverses its input looking for a Filter to discover the time range to gap fill. The InfluxQL plan would need to be constructed in such a way that those predicates can be discovered. I am fairly certain that it will, but I thought it was worth mentioning

As you mentioned elsewhere, InfluxQL OSS sets an implicit bounds from the timestamp of the oldest point to `now`.

We could mimic this behaviour in DataFusion, if we were able to use any expression for the time range. I realise today that `date_bin_gapfill` is limited to a Scalar value, but do you think it is possible to lift that restriction? If so, we could construct an InfluxQL plan similar to the following SQL:

```sql
SELECT 
  DATE_BIN_GAPFILL('30 seconds', time, '2001-01-01T00:00:00Z'::timestamp), 
  AVG(usage_idle)
FROM
  cpu
WHERE
  time >= (SELECT MIN(time) FROM cpu) AND time < NOW()
```

**Comment by wolffcm** [comment]
@stuartcarnie 

Currently the planner rule has a restriction that there must be a time range that it can find by traversing the plan, but the `GapFillExec` allows you to omit the lower bound, and it will just start filling gaps from the first point that it finds for each group:
https://github.com/influxdata/influxdb_iox/blob/9cd2a8816a8db2d60c7729632ae6e1440a3252fb/iox_query/src/exec/gapfill/mod.rs#L52-L56

I made the lower bound optional specifically to support InfluxQL. To get the default InfluxQL behavior the range can be set to `Range { start: Unbounded, end: Included(<call to NOW as an Expr>) }`.

If you want to use the planner rule `HandleGapFill` to do gap filling rather than constructing a `GapFill` node manually, I think the easiest thing would be to add a field to the rule itself called `require_time_range` or something like that. We can set it to true when planning InfluxQL queries and false for SQL. The rule could be updated to construct the right `GapFillParams` either way. Does that make sense?

**Comment by stuartcarnie** [comment]
> If you want to use the planner rule `HandleGapFill` to do gap filling rather than constructing a `GapFill` node manually, I think the easiest thing would be to add a field to the rule itself called `require_time_range` or something like that. We can set it to true when planning InfluxQL queries and false for SQL. The rule could be updated to construct the right `GapFillParams` either way. Does that make sense?

From what you are saying, I would not use the `date_bin_gapfill` function, but rather, create a `HandleGapFill` operator in the `InfluxQLToLogicalPlan` data type? If so, that makes sense to me.

**Comment by stuartcarnie** [comment]
I discovered that the time upper bound defaults to `now`, if an upper bound cannot be determined from the `WHERE` clause:

https://github.com/influxdata/influxdb/blob/98361e207349a3643bcc332d54b009818fe7585f/query/compile.go#L172-L176
