### ISSUE TITLE
FlightSQL Milestone 5: Complete Minimal FlightSQL API (enough for superset and grafana)

### ISSUE THREAD

**Issue by alamb** [influxdata/influxdb_iox#7210]
Milestone 5 of the design https://docs.google.com/document/d/1MtasrcQ-iBGZ2WgiXK-Lk6DevygtuSewoihOWag0kGU/edit#heading=h.hyufjffuq8v3

We are currently using an internal adapter called `queryrouterd`, that implements the missing FlightSQL in InfluxDB IOx

Definition of success is that the following  message types handled by `queryrouterd` are supported . Note this is a subset of messages that are defined in from https://github.com/apache/arrow/blob/main/format/FlightSql.proto

- [x] message `CommandGetCatalogs`: https://github.com/influxdata/influxdb_iox/pull/7212
- [x] message `CommandGetDbSchemas`: https://github.com/influxdata/influxdb_iox/pull/7213
- [ ] message `CommandGetTables`: 
      - Phase 1: https://github.com/influxdata/influxdb_iox/pull/7238
      - Phase 2: https://github.com/influxdata/influxdb_iox/pull/7289
      - Phase 3: https://github.com/influxdata/influxdb_iox/pull/7307
- [x] message `CommandGetTableTypes`: https://github.com/influxdata/influxdb_iox/pull/7242
- [x] message `CommandGetSqlInfo`: https://github.com/influxdata/influxdb_iox/pull/7198

Additional features are tracked in https://github.com/influxdata/influxdb_iox/issues/7265

## Reference Implementations
internal code reference: https://github.com/influxdata/idpe/blob/master/queryrouter/internal/server/flightsql_handler.go
Go package reference: https://pkg.go.dev/github.com/apache/arrow/go/v12/arrow/flight/flightsql

The golang implementation has a "BaseServer" that implements defaults for all messages. Mostly "unimplemented", e.g.  

https://github.com/apache/arrow/blob/44edc27e549d/go/arrow/flight/flightsql/server.go#L269

## Bonus Features
- [x] #7278

## Bugs
- [x] #7279

**Comment by mhilton** [comment]
We might need `CommandGetXdbcTypeInfo` in the fullness of time (I think the ODBC driver wants it). But `queryrouterd` has survived without it up until now.

**Comment by appletreeisyellow** [comment]
There is one last piece for `CommandGetTables` to be done before closing this issue, which is Phase 3: Support `include_schema` parameter. 

@alamb and I paired on this today and we are making progress on it. [Here](https://github.com/influxdata/influxdb_iox/tree/alamb/table_schema_binary) is the branch.
