### ISSUE TITLE
FlightSQL Metadata: Return an empty RecordBatch initially

### ISSUE THREAD

**Issue by appletreeisyellow** [influxdata/influxdb_iox#7486]
This issue is a subset of https://github.com/influxdata/influxdb_iox/issues/7265

@stuartcarnie found that `GetPrimaryKeys`, `CommandGetExportedKeys`, was used in CLion (internal [slack link](https://influxdata.slack.com/archives/C04K1QRSDFG/p1680137651670079))

Initially @alamb thinks to support the following metadata queries, we would just need to return an empty RecordBatch with the correct schema (as IOx doesn't expose its notion of primary keys from SQL)

- [x] FlightSQL Metadata: message CommandGetPrimaryKeys https://github.com/influxdata/influxdb_iox/pull/7496
- [x] FlightSQL Metadata: message CommandGetExportedKeys https://github.com/influxdata/influxdb_iox/pull/7532
- [x] FlightSQL Metadata: message CommandGetImportedKeys https://github.com/influxdata/influxdb_iox/pull/7546
- [ ] FlightSQL Metadata: message CommandGetCrossReference https://github.com/influxdata/influxdb_iox/pull/7548

**Comment by alamb** [comment]
https://docs.rs/arrow/latest/arrow/record_batch/struct.RecordBatch.html#method.new_empty is likely relevant.
