### ISSUE TITLE
How to proceed with the rest of the tasks to work correctly in both Serverless & CST

### ISSUE THREAD

**Issue by NGA-TRAN** [influxdata/influxdb_iox#8619]
We have been working on migrating `sort_key` which is a list of column names to `sort_key_ids` which is a list of column IDs. We are in the middle and so far we are very careful to do the work step-by-step because the PRs must be deployed in order and sometimes we need to wait for a few hours or a few days to verify everything works correctly before deploying the next PR.

Last week, we opened [this ticket](https://github.com/influxdata/k8s-idpe/issues/28555) saying the above process can be done with Serverless with careful steps from dev-team as described above. We need to do the same with CST and Clustered and there seems no clear way for that. Hence, we say `let us pause this migration`

To unpause the work, @8none1  suggests from the discussion [on slack](https://influxdata.slack.com/archives/CRK9M8L5Q/p1693319741731959) that while waiting for how to make CST, Clustered and even Serverless deal with in-order-migrations. we will continue this `sort_key to sort_key_ids migration` but continuing carefully doing what we have been done but also include CST folks to ensure PRs are deployed in CST in the same manner with Serverless.

So this ticket is to get everyone on board and the order of the PRs to get in.

### Here are the order.
NOTE: @NGA-TRAN will merge the PR one by one and after **each task** below is deployed, she will verify that things go correctly or fix them before moving to the next PR.

- [ ] https://github.com/influxdata/influxdb_iox/issues/8467 - **Actions:** 
        @crepererum and @NGA-TRAN to finish this up. **Status:** all 6 Serverless and 15 CST are migrated. One CST `PerfB` needs to get migrated.
- [ ] Tell CST stop deploying IOx - **Actions:** @NGA-TRAN & @cannonpalms agree on time frame
- [ ] https://github.com/influxdata/influxdb_iox/issues/8470 - **Actions:** @crepererum to review [the PR](https://github.com/influxdata/influxdb_iox/pull/8604)
- [ ] https://github.com/influxdata/influxdb_iox/issues/8558 - **Actions:**  @Joe-Blount to review [the PR](https://github.com/influxdata/influxdb_iox/pull/8575)
- [ ] https://github.com/influxdata/influxdb_iox/issues/8555 - **Actions:**  @domodwyer / @savage-engineer to review these 3 PRs: [PR1](https://github.com/influxdata/influxdb_iox/pull/8556), [PR2](https://github.com/influxdata/influxdb_iox/pull/8579), [PR3](https://github.com/influxdata/influxdb_iox/pull/8588).  The 3 PRs have to merge in that order because of the dependency but due to the nature of the work, they do NOT need to wait for the other to get deployed before them. That is why they are all in on task here
- [ ] Tell CST to continue the deployment which mean all PRs above that have been proved work correctly in Serverless in all Querier, Compactor and Ingester will be deployed in CST - Actions: @NGA-TRAN let @cannonpalms know
```

**Comment by cannonpalms** [comment]
I think the work needs to wait until we have been able to have a discussion. What's written here might work for dedicated (I haven't given it thorough thought because I believe we all need more time), but doesn't work for clustered. 


During the discussion slated for next week, myself and a few others had intended to suggest as a path forward doing the full compatibility dance: don't remove the old column, have the code fall back to sorting by column name if it can't sort by column IDs. Leave it in this state for a period of several months. Remove the fallback code and column at a later date. 

I'll let others tell me if this is possible.

The question of how long of a compatibility horizon is required is one currently being discussed elsewhere above my pay grade. It'll come down to the frequency with which we are comfortable requiring customers perform updates, and how many versions we require that they deploy in sequence when upgrading by more than 1 version at a time.

In the meantime, I don't think we should attempt to move forward with this work until we've been able to discuss and come to an agreement. If it is so urgent to continue work on this, let's move the discussion.

**Comment by domodwyer** [comment]
> don't remove the old column, have the code fall back to sorting by column name if it can't sort by column IDs. Leave it in this state for a period of several months. Remove the fallback code and column at a later date.

We need to frame this discussion in a broader context - not just this one change. There's several of these type of dependent changes **per week** in IOx.

You can't support an infinite history of catalog schemas - it's crippling complexity in an area of the system that already requires great care to not cause an outage, or worse, corruption.

Imagine having to understand how your change might interact with every catalog state in the last 6 months! It's a pure mathematical combination state space - try using a calculator to see how fast those numbers grow! Then combine that with "full compatibility support" for WAL disk formats, internal APIs, gossip message formats, persistent cache states, parquet file encoding strategies, features supported by peer nodes, the incoming parquet file cache service, and it goes on and on and on and only grows over time.

I know this answer seems so simple, but it's very problematic for development - for N changes, you have N different subtle variations of code, all doing very similar but slightly different things - it causes fragile code with a high risk of breakage by dev work and places an immense tech depth on everyone, for everything, going forwards.

What you're suggesting is just not practical, especially for a team our size.

---

Clustered aside, I think one thing I'm interested in understanding is _why we have this problem_ in CST in the first place - why are code changes batched up and released somewhat randomly? What's the requirement that leads to this situation?

If we did the normal continuous deployment thing, this would be a non-problem for CST.

**Comment by domodwyer** [comment]
I feel like an example of what I'm facing today might highlight the problem better:

Imagine we've gone the suggested route - we'll maintain the sort key in two states in the catalog; one encoding will use the name, the other will use the IDs, and we'll just figure it out at runtime based on what column is populated.

I'm currently developing a new feature that uses this sort key to gossip within the ingesters to improve persist performance - what do I gossip? If I wait a week, I can gossip IDs and be done with it, but realistically this support thing forces me to gossip both formats, deciding at runtime. There's a good chance name-based sort keys won't fit in a UDP packet, so now we have to disable that functionality for a subset of partitions, which will impact performance for a subset of partitions, making it seem "randomly slow" to users (the worst sort!). If we do try and support both, we have to duplicate the code because code operates on data, and the data is completely different.

The "support everything" creates a fork in the code, that every new addition has to account for. Worse still, despite the "support for 6 months" or whatever time frame is selected, that fork lives forever, it becomes so much work to go and unpick that change from the tens or hundreds of features added after it. We simply don't have the manpower to dedicate someone to full time unpicking (itself a high outage risk task).

As the support forks in code grow, so does the complexity, and it takes more and more options away from us in the future.

**Comment by 8none1** [comment]
Issue https://github.com/influxdata/k8s-idpe/issues/28555 was opened to track the overall problem of how to deploy code in to Serverless and CST in an orderly fashion.  If you have thoughts and ideas on that problem, please comment in the other issue.

My understanding is that this specific issue is to allow Nga to deploy her changes to serverless and CST in a managed way now, as a one off.  

Then we can close this issue and focus our energy on making sure we don't have the same problem in the future.

I would suggest that comments on the specifics of how to avoid or better deal with this problem in the future are better place in the other issue.

**Comment by domodwyer** [comment]
The gosisp thing above is real, and very tied to this sort key issue - I've been holding off implementing it until we've switched to IDs :+1:

**Comment by cannonpalms** [comment]
Let's move the broader discussion back to https://github.com/influxdata/k8s-idpe/issues/28555. I'll reply to your comments there, @domodwyer. In this issue, I only wanted to speak for this particular feature and how to move forward.

**Comment by NGA-TRAN** [comment]
Make this one resolved as we have agreed on the process
