### ISSUE TITLE
feat: add write and query routing to IOx

### ISSUE THREAD

**Issue by pauldix** [influxdata/influxdb_iox#916]
An IOx server should be able to operate as a router of incoming data and queries to other servers based on criteria like the table name, and/or one or more column values. It should be able to route specific matches to another IOx server, or hash the value and send it to a specific server in a collection based on its location in the ring.

Initially, we'll use this in our own environment to horizontally distribute the write workload, while still achieving data locality for query workloads (i.e. avoiding distributed query planning & execution). This can be thought of as sharding and we'll likely add complexity/capability over time.

This issue will serve as the tracker for the overall feature delivery. To get this done as a user facing feature, we'll need to deliver the following:

* [x] #917 - Add API and CLI to add IOx servers to the collection of nodes an IOx server is aware of
* [x] #918 - Add sharding rules to database rules
* [x] #1156 - Refactor ShardConfig to have ShardId
* [ ] #919 - Add sharding rules API and CLI
* [x] #920 - Implement write routing to remote IOx server
* [ ] #921 - Implement read routing to remote IOx server 

While doing this work, it should clean up cruft and older logic/organization from database rules.

**Comment by crepererum** [comment]
Closing this since we have the contained issues (#919, #921) in new GitHub-based epics.
